### ISSUE TITLE
Allow wifi Credentials to be re-configured after first boot.

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#102]
The new OS images auto mount a config partition that contains a config.json with the network settings.  There should be functionality like 
`$ sudo resin wifi config`
which will allow the user to select a SD card or device (edison) and either change the current wifi config or add an additional wifi SSID and Passphrase.

**Comment by jviotti** [comment]
I'd love to have this functionality in the CLI. There aww some things that need to be evaluated:

- We should be able to perform `operations` (https://github.com/resin-io/resin-device-operations) in a plugged device. We currently only do it for locally saved image files, but the module might support it automatically already. Needs testing.
- Plan the command name, behaviour, extra options, etc.

**Comment by shaunmulligan** [comment]
currently also blocked on the device side because the config.json is only read on first boot.

**Comment by jviotti** [comment]
@pcarranzav Can you provide some update regarding this blocker?

**Comment by jviotti** [comment]
The `config.json` is now read on every boot!

**Comment by jviotti** [comment]
Also, I can confirm all the modules work with raw devices directly, so we have everything in place to build this feature.

**Comment by jviotti** [comment]
Implement `resin config reconfigure` for this purpose.
