### ISSUE TITLE
Use bmaptool SD card writing strategy to speed up card writing.

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#104]
Look in to either using [bmaptool](https://source.tizen.org/development/reference/bmaptool) or a similar strategy to improve writing speed of SD cards.

**Comment by jviotti** [comment]
This task needs serious studying of how `bmaptool` performs its job, and an actual implementation in a separate NPM module.

**Comment by jviotti** [comment]
I've studied `bmaptool` and it seems to use GNU/Linux specific features to perform it's job, but not sure it it's just the implementation or or necessarily requires those features, for example to get the host block size for the image. I also get the following error on OS X:

> The kernel or file-system does not support SEEK_HOLE and SEEK_DATA.

**Comment by petrosagg** [comment]
`bmaptool` accelerates the writing of images when said images are stored in a sparse file. A sparse file is a file that its reported size is larger than its size on disk. The acceleration comes from not writing the empty sections of the sparse files (holes) and only writing the data sections.

`SEEK_HOLE` and `SEEK_DATA` should only be needed for the initial creation of the hole/data map file and then it could be used by any operating system to write the blocks of data in the right offsets, you don't need the original sparse file at this point.

Our images are already stored as a sparse file on the build server:

```
$ du -h resin-image-raspberrypi2.resin-sdcard 
1.3G	resin-image-raspberrypi2.resin-sdcard
$ du -h --apparent-size resin-image-raspberrypi2.resin-sdcard 
1.5G	resin-image-raspberrypi2.resin-sdcard
```

This means we can save time by not writing those 200MB. Also, I have a suspicion that the image file could be even sparser by improving the creation of the btrfs partition in yocto.

**Comment by jviotti** [comment]
@petrosagg What about generating the map file server side? `bmaptool` exposes a command for that.

This would be easier once we serve static un-configured images. Then, for example, I could fetch `/static/images/raspberry-pi.img` and `/static/images/raspberry-pi.img.map`.

**Comment by petrosagg** [comment]
Yes, that's exactly what I had in mind.

**Comment by jviotti** [comment]
I'm closing this since the feature will be implemented in Etcher, whose backend is then re-used in the Resin CLI: https://github.com/resin-io/etcher/issues/171
