### ISSUE TITLE
"Try running as sudo" thrown when SD card lock is in place

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#105]
If the user inserts a card which has the physical lock enabled on it. The CLI tells the user they should try run the command as sudo, even though they have run as sudo.

example:
```
resin-io:~ hobochild$ sudo resin device init --application 9july2015
? Drive: /dev/disk2 (*8.0 GB) - FDisk_partition_scheme
? This will completely erase /dev/disk2. Are you sure you want to continue? Yes
? Network Type: ethernet
Checking application: 9july2015
Getting device manifest for the application
Fetching application configuration
Associating the device
Configuring device operating system image
The base image was cached to improve initialization time of similar devices
Attempting to write operating system image to drive
You don't have enough privileges to run this operation.
Try running this command again prefixing it with `sudo`.
```

**Comment by jviotti** [comment]
I don't think we have a reliable way of detecting the lock status of an sdcard (happy to be proven incorrect).

The approaches I can think of are:

- Extending the error message to say something like: "If you're writing to an SDCard, make sure is not locked".
- Documenting this potential issue in the docs.
- Showing an information message at the start of `device init` remembering the user to make sure his sdcard is not locked.

What do you think?

**Comment by shaunmulligan** [comment]
I think we just need to extend the error message and document
