### ISSUE TITLE
Reword output when download is happening in device init.

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#106]
when downloads happens in quickstart, current text is:
`Configuring device operating system image`
possibly change to or include this line as well  `Downloading device operating system`

**Comment by jviotti** [comment]
The process of fetching an image is encapsulated by https://github.com/resin-io/resin-image-manager, and there is no easy way for the CLI to now if the image is going to be grabbed from the cache, or re-downloaded it.

Currently, if the image needs to be downloaded, a progress bar will appear which contains the following label: `Downloading Device OS`.

Is this enough to inform the user of a download taking place?

**Comment by shaunmulligan** [comment]
change "configuring" --> "Initializing"
