### ISSUE TITLE
cd to associated project folder automatically for the user.

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#108]
once you have associated your folder to the app, it tells you this:
* Please type "git push resin master" into your project directory now!
* it would be better i think if it told you that it was changing directory to the associated location, then changed you to this directory and finally told you to run “git push resin master" command.

**Comment by jviotti** [comment]
I don't think we can change the current directory from outside our process, so this is not under our control.

I suggest replacing the final message with:

```sh
Please type:

    $ cd <the project path> && git push resin master

To push your project to resin.io.
```

**Comment by shaunmulligan** [comment]
sounds good to me
