### ISSUE TITLE
Repeated output when copying token in Ubuntu

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-cli#11]
Pasting the Auth Token into the terminal, the CLI shows the token repeated several times. Login works, but UI looks weird.
![screenshot from 2015-04-08 12 18 52 - censored](https://cloud.githubusercontent.com/assets/2223590/7048712/066b9774-ddeb-11e4-8628-544ddaa1eb91.png)

**Comment by jviotti** [comment]
I can reproduce in both `gnome-terminal` and `terminator`. Probably an issue with [inquirer](https://github.com/SBoudrias/Inquirer.js/).

**Comment by jviotti** [comment]
It seems to happen with every inquirer input once the input exceeds the width of the terminal.

**Comment by jviotti** [comment]
Related: https://github.com/SBoudrias/Inquirer.js/issues/214.

**Comment by jviotti** [comment]
Fixed in https://github.com/SBoudrias/Inquirer.js/pull/239. I'll close the issue once the PR is merged and released.

**Comment by jviotti** [comment]
Added a workaround in https://github.com/resin-io/resin-cli-visuals/pull/14, until the issue get's fixed in Inquirer.
