### ISSUE TITLE
bug in y/n input cases

### ISSUE THREAD

**Issue by mkorakakis** [resin-io/resin-cli#116]
CLI sets as No any input besides y/N automatically.

example:
```
? Are you sure you want to associate C:\Users\korakas\Documents\GitHub\resin-cli with asdsa? (y/N) h
? Are you sure you want to associate C:\Users\korakas\Documents\GitHub\resin-cli with asdsa? No
```

**Comment by jviotti** [comment]
This is an issue with https://github.com/SBoudrias/Inquirer.js, which I'm not sure what's the behaviour most people expect.

Can you move this concern to inquirerjs, and discuss the correct approach there?

I'll close this ticket since it's not directly related to the Resin CLI.
