### ISSUE TITLE
Implement a command option for "resin init" to allow customising the application name independently from the current directory

### ISSUE THREAD

**Issue by mkorakakis** [resin-io/resin-cli#128]
The command displays, besides the actual question, also the folder from where I run it.

Example:

```
C:\Users\korakas\Documents\GitHub>node ./resin-cli/bin/resin init
? What is the name of your application? (GitHub)
```

In this case, `resin init` default the application name to the current directory (or the directory specified with `--project`) name. 

For scripting reasons, it'd be nice to allow a new `--name` option that customises the application name. For example:

```
C:\Users\korakas\Documents\GitHub>node ./resin-cli/bin/resin init --name MyAppName
```

**Comment by jviotti** [comment]
The `resin init` command is going to be removed in a pending PR (as part of the CLI slimming down process), so closing this issue.
