### ISSUE TITLE
resin logs doesn't fail with an invalid uuid

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-cli#13]
If I run `resin logs whatever` (sic), it just hangs there. It would be nice to have an error message like "Device doesn't exist".

**Comment by pcarranzav** [comment]
Ah, sorry, I hadn't seen the help message that addresses this limitation.

**Comment by jviotti** [comment]
Fixed in the SDK (https://github.com/resin-io/resin-sdk/commit/0ec4fd4db6767bc8e37d891ac55c9e7328bfe1ee). The fix will land in the next CLI release soon.
