### ISSUE TITLE
resin devices is a little unclear

### ISSUE THREAD

**Issue by lorenzo-stoakes** [resin-io/resin-cli#18]
Running `resin devices [app name or id]` simply returns the original help page. 

After discussion it seems this requires `-a [app name]` `--app [app name]` or `--application [app name]`, so I think either this should return a specific error messages saying `specify application using -a [app name]` or equivalent, or the command I mentioned above should also be accepted (which would be my preference overall :)

**Comment by jviotti** [comment]
Addressed in https://github.com/resin-io/resin-cli/pull/29.
