### ISSUE TITLE
docs, login section points users to wrong url.

### ISSUE THREAD

**Issue by nchronas** [resin-io/resin-cli#182]
The url in Authentication, login [token] should be :
https://dashboard.resin.io/preferences

instead of
https://dashboard.resinstaging.io/preferences

**Comment by jviotti** [comment]
Hi @nchronas, thanks for reporting. 

I'm fixing the generated documentation from the CLI side, but make sure to open a relevant issue on the Resin Docs GitHub repository (https://github.com/resin-io/docs) so they pull the latest version once my PR is merged to `master`.

**Comment by jviotti** [comment]
Merged!
