### ISSUE TITLE
Expose a command to generate API Keys

### ISSUE THREAD

**Issue by jviotti** [resin-io/resin-cli#191]
This command will allow the user to generate ~~application/device specific API keys will can later be used in their applications.~~ per-user api keys (for now, we can extend to different scopes later, as that becomes possible)

**Comment by jviotti** [comment]
Blocked by API keys needing to be implemented the correct way in the API.

**Comment by thgreasi** [comment]
HQ: https://github.com/resin-io/hq/pull/861
