### ISSUE TITLE
Device types still display (PREVIEW) and (EXPERIEMENTAL)

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#213]
The device types still show the old tags. they are now referred to as (ALPHA) and (BETA)

**Comment by jviotti** [comment]
@shaunmulligan The CLI doesn't hardcode any names. They come from the `/config` endpoint from the API, so probably they wasn't changed there. I'll double check.

**Comment by jviotti** [comment]
@shaunmulligan I've checked and indeed the `deviceTypes` object returned by `GET /config` returns names containing PREVIEW and EXPERIMENTAL.

Closing since the source of the issue is not the CLI.
