### ISSUE TITLE
Suggestion: Make it accept the API key when it's in the C&P buffer

### ISSUE THREAD

**Issue by ErikDeBruijn** [resin-io/resin-cli#216]
On linux and Mac you can get the paste buffer easily (e.g. `pbpaste` on OS X). It might be cool if upon pressing the copy token button in the webpage that pops up, it would accept the key. 

Alternatively, you could let it generate a key, open the URL with the key in it and in the web-interface you'd accept it (or then copy it to the clipboard). This would be a flow that people know from authorizing a app to post on Twitter or Facebook.

Just my 5ct.

**Comment by jviotti** [comment]
Hi @ErikDeBruijn ,

That is a great idea. The plan was to build a Node-Webkit application that opened the login page from the dashboard and automatically log you in the CLI after authentication.

The paster buffer was something we didn't consider before, however I wonder how we can detect from the CLI that the token was copied into the buffer (maybe polling the buffer for something that matches a specific regex?).

**Comment by jviotti** [comment]
Hi @ErikDeBruijn ,

Based on your suggestion, we've been working hard towards a best way to deal with authentication:

Soon, once the dashboard opens in your browser, you'll be prompted to "Authorise" the CLI to use your account (similar to OAuth), and on agreement, the dashboard will exchange the token with the CLI automatically, without having to manually copy and paste.

See https://github.com/resin-io/resin-cli/pull/272

**Comment by ErikDeBruijn** [comment]
That's pretty awesome! Thanks for incorporating the feedback!

**Comment by jviotti** [comment]
@ErikDeBruijn You're welcome, thanks to you for the feedback! 

BTW, the feature commented above was already released to NPM as v2.4.0.
