### ISSUE TITLE
Perhaps add sudo to update prompt

### ISSUE THREAD

**Issue by craig-mulligan** [resin-io/resin-cli#223]
When you run `resin version` it prompts you to update with text `Run npm install -g resin-cli to update` But I got an access error, it maybe specific to my setup, but is it not safer just to add sudo to the prompt?

**Comment by jviotti** [comment]
@craig-mulligan I think it's best to clarify below that depending on the environment you may need administrator privileges, since there are setups when `sudo` is not necessary, or may be even harmful.

**Comment by craig-mulligan** [comment]
Sounds good

**Comment by jviotti** [comment]
@craig-mulligan PR sent. Can you quickly review message?
