### ISSUE TITLE
Since updating to 1.1.0 I get this error print

### ISSUE THREAD

**Issue by craig-mulligan** [resin-io/resin-cli#224]
Since updating to 1.1.0 I get this strange error.
```
➜  ~  sudo resin quickstart
Password:

/usr/local/lib/node_modules/resin-plugin-sync/node_modules/watchr/node_modules/taskgroup/node_modules/ambi/es6/lib/ambi.js:5
export default function ambi (method, ...args) {
^^^^^^
? Select an application (Use arrow keys)
❯ Create a new application 
  BBBtest 
  CLItest 
  Dreamy 
```

**Comment by jviotti** [comment]
@craig-mulligan That looks like ES6 syntax coming from one of Resin Sync plugin dependencies. Since the error happens in the plugin and not in the CLI, can you move this issue to https://github.com/resin-io/resin-plugin-sync?
