### ISSUE TITLE
Occasionally getting timeouts

### ISSUE THREAD

**Issue by craig-mulligan** [resin-io/resin-cli#225]
```
? Select an application myApp
Getting device operating system for raspberry-pi2
The image was downloaded to /tmp/tmp-33188j7BjjFYfK80a
Registering to myApp: 38c670e184dfcd000f0b44cebcbc10aac30578f3dc19988aacc7b17f92d22a
ETIMEDOUT: ETIMEDOUT
```

**Comment by jviotti** [comment]
Looks like a network issue when communicating with the API. Happy to clarify the message. Any suggestion?

**Comment by craig-mulligan** [comment]
Couldn't reach resin.io API, please check your connection and try again.

**Comment by craig-mulligan** [comment]
Maybe the API was slow at the time because page was deploying or smthing

**Comment by jviotti** [comment]
@craig-mulligan PR sent. Can you review the message? Notice I omitted the first part of your suggestion which mentions "Resin.io API" since this error can happen with any kind of request.
