### ISSUE TITLE
If no dashboard.resin.io page is open, CLI sits waiting for ages

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#286]
If I don't already have a browser tab open on resin dashboard when I try login to the CLI, then it never succeeds, even if I open the dashboard while its waiting to connect it doesnt seem to work. Had to kill the cli command and restart it.

**Comment by jviotti** [comment]
@shaunmulligan The browser tab is supposed to open no matter if your browser is not running, or you don't have a Resin.io tab opened already (I've just tested both cases to make sure).

Where are you running the CLI?

***

As a side note, I have a possible workaround to any potential browser issue:

- Allow the user to hit "enter" or any other key while the CLI awaits for the token to attempt to re-open the dashboard.

**Comment by shaunmulligan** [comment]
Okay, actually I can't reproduce it anymore :anguished: I thought it might be because I use multiple different profiles on chrome, but it works all the time now. So i will close this.
