### ISSUE TITLE
Add command to reboot device

### ISSUE THREAD

**Issue by blalor** [resin-io/resin-cli#319]

**Comment by jviotti** [comment]
Hey there, thanks for reaching out!

This is a great suggestion, which can be implemented using the [Resin Supervisor API](http://docs.resin.io/#/pages/runtime/supervisor-api.md#post-v1-reboot).

I'm opening a new issue in the NodeJS Resin SDK project to add support for this, and then we can expose a CLI command for it.

**Comment by jviotti** [comment]
This feature was released in v2.7.0.
