### ISSUE TITLE
Resin Sync should follow the `COPY` commands from the Dockerfile

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#350]
It would be useful if resin sync could figure how how to correctly sync files based on the `COPY` commands it reads in the Dockerfile.

**Comment by jviotti** [comment]
@shaunmulligan I think a better place for this issue would be the https://github.com/resin-io-modules/resin-sync project, since that's where the sync logic is implemented.

I'll move it for you and close this one.
