### ISSUE TITLE
Better wording in `config` resin cli commands

### ISSUE THREAD

**Issue by lekkas** [resin-io/resin-cli#351]
IMHO `Use this command to inject a config.json file to the SD card of a provisioned device` is more accurate and less confusing than the current `Use this command to inject a config.json file to a provisioned device`. 

Sending a PR shortly, feel free to accept/reject on taste.

**Comment by jviotti** [comment]
Hi @lekkas ,

Good point, but please consider the following case when sending the PR:

- There might be devices using another form of removable drive that is not an SD Card. We shouldn't hardcode "SDCard" here IMO.

Happy to accept it though, makes a lot of sense.

**Comment by lekkas** [comment]
Right, good point, I'm biased with having all those SD card enabled devices hanging around.

How about `[...] inject a config.json file to the mounted filesystem (e.g. SD card) of a provisioned device`

?

**Comment by jviotti** [comment]
Looks perfect to me!
