### ISSUE TITLE
Go to Dashboard link after web authorization with RESINRC_RESIN_URL

### ISSUE THREAD

**Issue by imrehg** [resin-io/resin-cli#358]
When using resin-cli for staging as `RESINRC_RESIN_URL=resinstaging.io resin login`, I use use the web authentication. It logs me in fine, but the final "go to dashboard" button (on the page served locally) points at `dashboard.resin.io` instead of the expected `dashboard.resinstaging.io` based on the env variable. (updated)

**Comment by emirotin** [comment]
Typo? The last URL should be `dashboard.resinstaging.io`

**Comment by imrehg** [comment]
Yup, sorry, corrected.

**Comment by jviotti** [comment]
Ah, true. Turn's out the URL is hardcoded on such page (https://github.com/resin-io/resin-cli-auth/blob/master/pages/success.html#L18). Some tempting magic should fix it.

**Comment by pimterry** [comment]
This was fixed a little while ago in resin-cli-auth 1.2.0
