### ISSUE TITLE
resin ssh: doesn't work with ECDSA key

### ISSUE THREAD

**Issue by villaseca** [resin-io/resin-cli#377]
After I tried to log in to a running device it says "Permission denied (publickey)". Checked with RSA and it worked fine.

**Comment by imrehg** [comment]
It's mentioned in the docs, but admittedly not very well (only in the getting started guides, eg. [this one](http://docs.resin.io/raspberrypi3/python/getting-started/#some-notes-and-caveats-on-resin-sync))

As far as I remember, it's the limitation of the current, lightweight ssh server running on the device, that is in the process of being replaced with a full-featured one (can't seem to find related issues, though, this is what I remember)

**Comment by lekkas** [comment]
Hey @villaseca @imrehg ,

Thanks for the report!

Indeed this is a known issue on the ssh gateway side. The ticket is tracked internally, but let's leave this one open as well to make this limitation more clear.

**Comment by lekkas** [comment]
Hey @imrehg @villaseca, a quick update on this. 

Both `resin sync` and `resin ssh` now work with ECDSA keys and [the docs have been updated as well](http://docs.resin.io/raspberrypi3/cpp/getting-started/#some-notes-and-caveats-on-resin-sync).

Cheers!
