### ISSUE TITLE
`resin logs <UUID>` truncates log output

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#380]
`resin logs <UUID>` truncates log output, even though the online guide says:

> By default, the command prints all log messages and exit.

**Comment by pimterry** [comment]
Since we're replacing all our logs infrastructure, which will include a bunch of the CLI & SDK logic, I'm going to close this. If it's still an issue in the big logs update we'll see it again there and we can fix it as part of that.
