### ISSUE TITLE
There is no notion of "Config Env Vars" on the cli

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#381]
On the UI we have split envars, so we now have `RESIN_` special envars referred to as "Config Vars" but there is no equivalent on the CLI or SDK for that matter.

**Comment by shaunmulligan** [comment]
additionally the `resin config` command can be confused with this feature

**Comment by imrehg** [comment]
Very much needed indeed!
Looking at the options, I think adding a new flag to `resin envs` and `resin env add|rename|rm` to work with config vars would be a better place. For example already has notion of app env vars and device env vars, (as it will be needed for "fleet config" and "device config").

Eg. `env add RESIN_SUPERVISOR_DELTA 1 --device <UUID> --config`

**Comment by brownjohnf** [comment]
I was talking with @pcarranzav recently, and if I understood him correctly, the supervisor has no notion of config vs. env vars. I think it's confusing to the user to split them anywhere, including the UI (I know it confuses me). Is there a compelling reason we've kept them separate? Why not just indicate that any var beginning with RESIN_ will be treated differently by the supervisor, and put some nice UX around that in the dashboard?

**Comment by pcarranzav** [comment]
It's the API that has (mostly) no notion of config vars, and stores both env and config vars in the same table.
The config/env split is done on the device state endpoint and the supervisor does distinguish between the two.
The original UI had env and config together, and then the split came to clarify the difference, and then the supervisor at some point stopped exposing the config vars to the app.
I think by now the differentiation is necessary, but I agree that we need a better UX around them.

**Comment by pimterry** [comment]
This is no longer relevant, because we're going to rewrite all this entirely shortly for multicontainer support. I'm going to close this, we'll end up redesigning how the CLI should expose config/service vars as part of that work anyway.
