### ISSUE TITLE
public-url: wrong URL while getting it with the shortened UUID

### ISSUE THREAD

**Issue by villaseca** [resin-io/resin-cli#388]
Using `resin device public-url <shortened-uuid>` returns a URL with the shortened UUID instead of the complete UUID.

Example:

> `resin device public-url de224ab`
> https://de224ab.resindevice.io

**Comment by craig-mulligan** [comment]
Hey, thanks for reporting. You are right, the supplied uuid is used to compose the returned url. We should fetch the full one instead. The method must have been implemented before we accepted shortened UUIDs. https://github.com/resin-io/resin-sdk/blob/master/lib/models/device.coffee#L1119

I'll take a look at it.

**Comment by craig-mulligan** [comment]
@villaseca I didn't realise that was you Thomas. I won't be so polite next time 😝

**Comment by villaseca** [comment]
@craig-mulligan Bring it on 😁

**Comment by pimterry** [comment]
Fixed ages ago, closing.
