### ISSUE TITLE
Enter running application container

### ISSUE THREAD

**Issue by agherzan** [resin-io/resin-cli#399]
# Description

Get a shell into a running application container using Resin CLI _`resin ssh`_ command.
# Steps to reproduce issue
1. Install resin cli with _`npm i -g resin-cli`_
2. Login with _`resin login`_. If testing on staging, prepend `RESINRC_RESIN_URL=resinstaging.io` to this and all subsequent _`resin`_ commands.
3. Create a single-container test application and provision a device with it.
4. Wait until the application is marked as running on the dashboard.
5. Run _`resin devices`_ to get the device uuid.
6. Ensure that your resin account has at least one RSA or DSA key -preferably RSA- that is also loaded in your ssh-agent. Use `ssh-add -l` to check the loaded keys.
7. Run _`time resin ssh <short device uuid>`_. For staging run _`time RESINRC_RESIN_URL=resinstaging.io resin ssh <short device uuid>`_
# Expected result
- A shell prompt (e.g. `bash-4.3#`) should appear after a few seconds.
- Running _'env | grep RESIN'_ should return a list of environment variables.
# Actual result

$ RESINRC_RESIN_URL=resinstaging.io resin ssh d64a5a0

   ╭──────────────────────────────────────╮
   │                                      │
   │   Update available 5.0.0 → 5.1.0     │
   │   Run npm i -g resin-cli to update   │
   │                                      │
   ╰──────────────────────────────────────╯

Notice that you might need administrator privileges depending on your setup

Connecting with: d64a5a0
ResinRequestError: Request error: tunneling socket could not be established, cause=socket hang up

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/resin-io/resin-cli/issues/new
  Gitter: https://gitter.im/resin-io/chat
# Other information

Reported by: Florin Sarbu 

Test configuration: VIA VAB820 

Test case number: TC13 

Test run: [https://resinio.testlodge.com/projects/16238/runs/230391?tab=2&run_section_id=253434&executed_case_id=10655751#executed_case_10655751](https://resinio.testlodge.com/projects/16238/runs/230391?tab=2&run_section_id=253434&executed_case_id=10655751#executed_case_10655751)

**Comment by lekkas** [comment]
See: https://github.com/resin-io/resin-cli/issues/400#issuecomment-312327392
