### ISSUE TITLE
Sync application container

### ISSUE THREAD

**Issue by agherzan** [resin-io/resin-cli#400]
# Description

Update code on a provisioned device using Resin CLI _`resin sync`_ command
# Steps to reproduce issue
1. Install resin cli with _`npm i -g resin-cli`_
2. Login with _`resin login`_. If testing on staging, prepend RESINRC_RESIN_URL=resinstaging.io to this and all subsequent `resin` commands.
3. Clone [this test node js application](https://github.com/resin-io-projects/simple-server-node) on your laptop and provision a device with it. 
4. Wait until the application is marked as running on the dashboard.
5. Enable and navigate to the Public Device URL. Confirm that the web server shows a `Hello World` message.
6. Edit `server.js` of the cloned application so that `res.send()` returns a different message, e.g. `res.send('Hello Resin Sync!')`
7. Run _`resin devices`_ to get the device uuid of the provisioned device.
8. Ensure that your resin account has at least one RSA or DSA key -preferably RSA- that is also loaded in your ssh-agent. Use `ssh-add -l` to check the loaded keys.
9. Run _`time resin sync <short device uuid> -s . -d /usr/src/app`_ within the test application folder (i.e. the folder of the edited `server.js` file). For staging run _`time RESINRC_RESIN_URL=resinstaging.io resin sync <short device uuid> -s . -d /usr/src/app`_
# Expected result

Expected result
- The sync process should start with status messages appearing on each step ('Stopping application container...', 'Syncing..', 'Starting application container...').
- At the end of _`resin sync`_ a "resin sync completed successfully!" message should appear.
- The device's Public Device URL should now show the new message, e.g. 'Hello Resin Sync!'
# Actual result

$ RESINRC_RESIN_URL=resinstaging.io resin sync d64a5a0 -s .

   ╭──────────────────────────────────────╮
   │                                      │
   │   Update available 5.0.0 → 5.1.0     │
   │   Run npm i -g resin-cli to update   │
   │                                      │
   ╰──────────────────────────────────────╯

Notice that you might need administrator privileges depending on your setup

? Destination directory on device [/usr/src/app] 
Getting information for device: d64a5a0
resin sync failed. ResinRequestError: Request error: tunneling socket could not be established, cause=socket hang up
# Other information

Reported by: Florin Sarbu 

Test configuration: VIA VAB820 

Test case number: TC14 

Test run: [https://resinio.testlodge.com/projects/16238/runs/230391?tab=2&run_section_id=253434&executed_case_id=10655752#executed_case_10655752](https://resinio.testlodge.com/projects/16238/runs/230391?tab=2&run_section_id=253434&executed_case_id=10655752#executed_case_10655752)

**Comment by lekkas** [comment]
`ResinRequestError: Request error: tunneling socket could not be established, cause=socket hang up` generally means that the device was not accessible via the VPN. This usually means that either the device has not come up online yet (i.e. has not connected to OpenVPN) or that its connected but the specific service/port wasn't accessible from the VPN interface.

The former case is generally self-correcting, when the device eventually comes up online. In the latter case, we need more investigation. So in any case, we can close this ticket since we don't have more information about what happened in this particular case.
