### ISSUE TITLE
Fix cmd.exe documentation error

### ISSUE THREAD

**Issue by lekkas** [resin-io/resin-cli#414]
`resin sync` and `resin ssh` JSDoc mention that cmd.exe can be used in Windows, which is wrong or at best, incomplete, since there are other dependencies as well (e.g. `rsync` for `resin sync`)

**Comment by imrehg** [comment]
Came up in the forums too, and info would be appreciated what other dependencies are there for `resin ssh` and `resin sync`. https://forums.resin.io/t/windows-resin-cli-ssh/515

**Comment by lekkas** [comment]
Thanks for the heads up @imrehg, a fix is on the way, I will update the documentation accordingly. 

In the meantime, we recommend using a bash-compatible shell (e.g. Bash for Windows 10 or [Git Bash](https://git-for-windows.github.io/) with `ssh` and `rsync` (the latter is only required by `resin sync`) to be correctly set up in the shell environment. The `cmd.exe` shell is not fully tested and required extra packages to be installed - we've only tested MinGW so far and the instructions can be found [here](https://github.com/resin-io-modules/resin-sync#for-windows-users)

**Comment by lekkas** [comment]
Landed in resin-cli@5.2.4
