### ISSUE TITLE
resin ssh only allows you to login into devices that you have provisioned

### ISSUE THREAD

**Issue by alberttwong** [resin-io/resin-cli#422]
I work with other people.   I can only `resin ssh` to my device but I cannot `resin ssh` to my team mate's device device.   

as a developer/ops person, I want all members who are collaborators to be able to ssh to any device that is member of the application so that they can login and make changes to the device and use resin cli tools (sync, ssh).

**Comment by lekkas** [comment]
Hey @alberttwong , 

Thank you for raising this.

Your use case makes perfect sense and we are already working on a fix for that will allow you use both `resin sync` and `resin ssh` to your teammate's devices. This requires a few backend changes to be deployed first, so I will ping you in this ticket as soon as accessing collaborator devices is available. While I can't give an exact ETA, the changes required are not very complex so I'd expect this to land in production within the next couple of weeks.

**Comment by lekkas** [comment]
Hey @alberttwong @nexflo a quick update on this. Unfortunately this has proven to be more complex that we initially thought. Although a Pull Request has already been opened in our backend to support collaborator access, the discussion is still ongoing and we are already past the two-week window I'm mentioning above so I'd like to let you know. I will ping you again as soon as we have an ETA.

**Comment by alberttwong** [comment]
That's okay.  What I did as a work around was to generate another ssh key and share it with my teammates.   Not perfect but works.

**Comment by lekkas** [comment]
Hey @alberttwong , this is fixed in resin-cli@6.1.0 so you might want to update your CLI . Collaborators can now use `resin ssh` and `resin sync` .
