### ISSUE TITLE
Clear logs functionality is missing

### ISSUE THREAD

**Issue by emirotin** [resin-io/resin-cli#446]
Right now the CLI differs from the UI in two ways (wrt device logs):
- it does not have the `clear` command for logs
- the logs history retrieved ignores the `clear` commands sent from the UI

The newest SDK (since 6.0.0-beta5) has the new methods:
- https://github.com/resin-io/resin-sdk/blob/master/DOCUMENTATION.md#resin.logs.clear (the new method)
- https://github.com/resin-io/resin-sdk/blob/master/DOCUMENTATION.md#logshistorysincelastclearuuidorid-options--promise (a drop-in replacement for `history` that only retrieves the logs after the most recent clear call)

I think the CLI should begin using the `historySinceLastClear` method by default and maybe (probably) allow a flag like `--all` that will use the `history` method.

Also the SDK now allows passing the options object to the history request (both methods), including the `{ count: N }` option. By default (current behavior) the history only returns 100 recent lines.
`historySinceLastClear` by default returns 200 lines (same as the UI).

**Comment by pimterry** [comment]
Closing for now since we're rebuilding all of how logs work shortly anyway - we'll consider adding clear logs functionality as part of that, but it's not critical anyway I think.
