### ISSUE TITLE
Login with --token broken

### ISSUE THREAD

**Issue by BrianAdams** [resin-io/resin-cli#447]
Version 5.5.0

Logging in using the --token option appears to work, but subsequent commands fail with session token expired error.

If I use just "resin login" and choose token from the menu, everything works correctly. 

This error makes it really hard to properly script some tasks.

>resin login --token $TOKEN
```
______          _         _
| ___ \        (_)       (_)
| |_/ /___  ___ _ _ __    _  ___
|    // _ \/ __| | '_ \  | |/ _ \
| |\ \  __/\__ \ | | | |_| | (_) |
\_| \_\___||___/_|_| |_(_)_|\___/

Logging in to resin.io
Successfully logged in as: gh_brianadams

Now what?

Run the following command to get a device started with Resin.io

  $ resin quickstart

Find out about more super powers by running:

  $ resin help

If you need help, or just want to say hi, don't hesitate in reaching out at:

  GitHub: https://github.com/resin-io/resin-cli/issues/new
  Gitter: https://gitter.im/resin-io/chat
```
> resin devices
```
Looks like your session token is expired.

Please try logging in again with:

	$ resin login

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/resin-io/resin-cli/issues/new
  Gitter: https://gitter.im/resin-io/chat
```

> resin login
```
______          _         _
| ___ \        (_)       (_)
| |_/ /___  ___ _ _ __    _  ___
|    // _ \/ __| | '_ \  | |/ _ \
| |\ \  __/\__ \ | | | |_| | (_) |
\_| \_\___||___/_|_| |_(_)_|\___/

Logging in to resin.io
? How would you like to login? Authentication token
? Token (from the preferences page) $TOKEN
Successfully logged in as: gh_brianadams

Now what?

Run the following command to get a device started with Resin.io

  $ resin quickstart

Find out about more super powers by running:

  $ resin help

If you need help, or just want to say hi, don't hesitate in reaching out at:

  GitHub: https://github.com/resin-io/resin-cli/issues/new
  Gitter: https://gitter.im/resin-io/chat
```
> resin devices
```
ID     UUID    NAME                    DEVICE TYPE      APPLICATION NAME   STATUS      IS ONLINE SUPERVISOR VERSION OS VERSION
```

**Comment by imrehg** [comment]
Hi, have you used a new token from the dashboard to log in? Those tokens have 1 week lifetime, so if you are trying to use an older token (I guess) something like this might happen?

Just tested `resin login --token "..."` followed by a `resin devices` on the latest `5.7.0` version, and token login works just fine.

**Comment by BrianAdams** [comment]
Thanks. Did not know about the expiration on the dashboard tokens.  Is there another suggested means for creating tokens that can be used on build servers (don't expire).

**Comment by imrehg** [comment]
@BrianAdams this question came up [in the forums this week too](https://forums.resin.io/t/auth-token-without-expiration-to-use-api/302), there's now open issue for it on this repo, you can subscribe to that: https://github.com/resin-io/resin-cli/issues/465
