### ISSUE TITLE
Path separators on resin local push don't work on Windows

### ISSUE THREAD

**Issue by CameronDiver** [resin-io/resin-cli#448]
At the hackathon somebody using windows attempted to use local mode and it all went fine, until a path was tried to use on windows that used backslashes `\`. I unfortunately don't have any stack traces or error messages due to the nature of finding it at the hackathon, and also I don't have windows so I can't reproduce.

It looked to me like `path.sep` was being used for something which was always going to need `/`.

**Comment by pimterry** [comment]
Fixed in 6.6.7
