### ISSUE TITLE
The shutdown and reboot device commands do not work

### ISSUE THREAD

**Issue by horia-delicoti** [resin-io/resin-cli#449]
When trying to shut down a device with command: "resin device shutdown <device_uuid> " , the response I get is " _ is not defined "

**Comment by pimterry** [comment]
A fix for this is now open in the SDK, this will be resolved as soon as that's ready and the cli is updated to the new resin-sdk (probably anything > `6.0.0-beta5`).

**Comment by pimterry** [comment]
Damn, github autoclosed this - it's actually still in progress

**Comment by pimterry** [comment]
This is now resolved as part of version 5.6.0.
