### ISSUE TITLE
Flag to not prompt (useful for scripts)

### ISSUE THREAD

**Issue by jviotti** [resin-io/resin-cli#45]
From @lorenzo-stoakes.

A flag to prevent y/n questions, e.g. --noconfirm.

**Comment by jviotti** [comment]
All commands that require confirmation accept a `--yes/-y` options. I'll close unless there is a specific command that is not working as expected.

**Comment by lorenzo-stoakes** [comment]
I've noticed the following:-

```bash
[~]$ resin app rm -y foobar
Application not found: rm
```

Which combines a couple of issues, the first being that since `app rm` is listed a separate command from `app`, it would follow that the `-y`ought to be where it is shown above. The second issue (perhaps ought to be broken out from this one) is that when there are more than the expected number of arguments, it seems to revert to the default of showing apps - I would have expected `resin app rm` to be an entirely separate command.

I wonder whether it might make more sense to use a separator that isn't whitespace to make it clear that this is a separate command? Comparing to a couple of other CLI tools - heroku uses `:` so it would be `resin app:rm` and git uses `-` so you'd do something like `resin app-rm` of course we could also guess that `resin app rm` meant `resin app-rm` or resin `app:rm`, but it is possible that we'll have a conflict - what if a user has an app called `rm`? I think the app name size restricts this right now, but for other commands this could become the case, plus we may remove these restrictions at some point.

We may need to separate these things out a bit from this issue @jviotti :)

**Comment by jviotti** [comment]
That's interesting. Let me investigate the command option issue as it may have a quick fix in Capitano.

About the name collision probability, this only happens when command prefixes are also a command on their own (for example "device associate" and “device”). A quick solution would be to convert “device” and “app” into “device info”, “app info” or “device ls”, “app ls".

**Comment by lorenzo-stoakes** [comment]
(ported from internal discussion :)

yeah, it's a trade off for sure @jviotti , but one worth thinking about. The ability to say something like `resin app foo` is handy however, and in this case we should consider the possibility of collisions, even if unlikely! Also in some ways 'resin foo-bar' or 'resin foo:bar' are a little clearer I think as it makes it really consistent that the pattern is 'resin [command] [args]' for people with small brains like me :)

**Comment by lorenzo-stoakes** [comment]
Also, it seems that the flag has to be put last in the command, which is very unusual:-

```
[~]$ resin -y app rm foo                                                                
Usage: resin [COMMAND] [OPTIONS]

Commands:

    version                       	output the version number
    help [command...]             	show help
    login [token]                 	login to resin.io
    logout                        	logout from resin.io
    signup                        	signup to resin.io
    whoami                        	get current username
    app create <name>             	create an application
    apps                          	list all applications
    app <name>                    	list a single application
    app rm <name>                 	remove an application
    app restart <name>            	restart an application
    app associate <name>          	associate a resin project
    init                          	init an application
    devices                       	list all devices
    devices supported             	list all supported devices
    device rename <name> [newName]	rename a resin device
    device init [device]          	initialise a device with resin os
    device <name>                 	list a single device
    device rm <name>              	remove a device
    device identify <uuid>        	identify a device with a UUID
    device await <name>           	await for a device to become online
    drives                        	list available drives
    note <|note>                  	set a device note
    preferences                   	open preferences form
    keys                          	list all ssh keys
    key add <name> [path]         	add a SSH key to resin.io
    key <id>                      	list a single ssh key
    key rm <id>                   	remove a ssh key
    envs                          	list all environment variables
    env add <key> [value]         	add an environment variable
    env rename <id> <value>       	rename an environment variable
    env rm <id>                   	remove an environment variable
    logs <uuid>                   	show device logs
    os download <name>            	download device OS
    os install <image> [device]   	write an operating system image to a device
    examples                      	list all example applications
    example clone <id>            	clone an example application
    example <id>                  	list a single example application
    plugins                       	list all plugins
    plugin install <name>         	install a plugin
    plugin update <name>          	update a plugin
    plugin rm <name>              	remove a plugin
    update                        	update the resin cli

Global Options:

    --quiet, -q         	quiet (no output)
    --project, -j <path>	project path
    --version, -v       	output the version number
    --no-color          	disable colour highlighting

[~]$ resin app -y rm foo                                                                
ID: 123456789
APP NAME: foo
DEVICE TYPE: raspberry-pi2
GIT REPOSITORY: <redacted>
COMMIT: <redacted>
[~]$ resin app rm -y foo
Application not found: rm
[~]$ resin app rm foo -y
[~]$ # Succeeded.
```

I'd expect that any of the first 3 possibilities would work, and the final one would fail :)

**Comment by jviotti** [comment]
@lorenzo-stoakes Can you move your last post to a different (new) GitHub issue, so I can work on it?

**Comment by lorenzo-stoakes** [comment]
@jviotti deleted and will create a new issue in just a moment!

**Comment by jviotti** [comment]
Closing issue since a new one was opened in Capitano for this purpose.
