### ISSUE TITLE
expecting an array or an iterable object but got [object Null]

### ISSUE THREAD

**Issue by emirotin** [resin-io/resin-cli#456]
https://github.com/resin-io/resin-cli/issues/452#issuecomment-288661711

My test account has passwordless sudo. When this code is ran
```
if os.platform() isnt 'win32'
  console.log('Type your computer password to continue')

return president.executeAsync(command)
```

it prints the message and then the control returns to the main program after a while.
During the `device init` the program then crashes with `expecting an array or an iterable object but got [object Null]` which I don't yet know where it's coming from.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1cbr)

**Comment by emirotin** [comment]
It may also be an issue for users having password for sudo, but after some sudo commands not having to enter it (as the OS caches it for a while and doesn't require for the consequent operations).

**Comment by emirotin** [comment]
It may be unrelated to the sudo password, there's a problem with multiarg promisification: https://github.com/petkaantonov/bluebird/issues/826

**Comment by lurch** [comment]
Dunno if it helps, but in Etcher we use `is-elevated` and `sudo-prompt`
https://github.com/resin-io/etcher/blob/master/lib/child-writer/writer-proxy.js

(although I've not tested it in a passwordless sudo environment)

**Comment by emirotin** [comment]
Thanks but I think it's unrelated. I now believe the bluebird stuff is the only actual problem.

**Comment by emirotin** [comment]
After digging 4 levels deep into the dependencies (all of which are our modules) I've found that we're using a very old version of `resin-image-write` (which has been even renamed since then), which does 

```
return fs.writeAsync(fd, buffer, 0, bufferSize, 0)
			.spread(function(bytesWritten) { ... }
```

The `spread` thing here fails because the writeAsync is not returning an array (instead it's a single callback argument).

I understand why it used to work: Bluebird v2 used to wrap the multiple callback args into an array when promisifying. But I have no idea why it has stopped working. I observe the behavior that of Bluebird v3 - only first argument is being passed, the 2nd callback argument (the stream itself) is discarded. Then the `.spread` is being called on a number and fails.

This really doesn't make much sense to me because I've verified that the Bluebird version in that module is v2. But nevertheless replacing `.spread` with `.then` fixes the issue.

I will work on making use of the recent etcher-image-write if possible.

**Comment by emirotin** [comment]
I can assume this somehow may be related to the version of Node (as Tim has mentioned the code has worked just some time ago), but still can't properly explain it.

**Comment by emirotin** [comment]
This issue was fixed upstream https://github.com/resin-io-modules/etcher-image-write/commit/de4655e6a572cd9eb094ca4e47fc29b62321800c but still why would it work for some people and not work for others?

**Comment by lurch** [comment]
Maybe this is something it might be worth @jviotti having a look at? Most of the Etcher code (and the modules used by it) is his baby ;)

**Comment by jviotti** [comment]
I'll take a look. @emirotin I'd also check the npm version. Some npm versions might be trying to be too smart when flattening `node_modules`, and somehow cause the module to use an incompatible Bluebird version.

**Comment by emirotin** [comment]
Thanks @lurch @jviotti but really I'm fine here. I mean I still don't know why it has happened, but I have identified the problem and already fixed it. It was previously fixed in the resin-image-write and this module was stuck on the old version. The PRs in resin-device-operations and resin-device-init fix this exact issue.
