### ISSUE TITLE
User Request: fully non-interactive mode for device init

### ISSUE THREAD

**Issue by emirotin** [resin-io/resin-cli#462]
That would need specifying the OS version and the device config (network, etc).

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1d9v)

**Comment by sonyagreen** [comment]
User wants to be informed when this is done (see Front conversation)

**Comment by emirotin** [comment]
I start working on this feature now

**Comment by emirotin** [comment]
Implemented, will go in the next resin-cli release
