### ISSUE TITLE
Warn if expired token is used to log in

### ISSUE THREAD

**Issue by imrehg** [resin-io/resin-cli#468]
Looks like `resin-cli` successfully logs in with an expired token but then none of the commands actually work: https://github.com/resin-io/resin-cli/issues/447 Should `resin login` time expired tokens be rejected, or warned about?

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1dyp)

**Comment by emirotin** [comment]
Great point, if it's the case indeed the warning must be issued and such token must be dropped.

**Comment by emirotin** [comment]
The key changes are here https://github.com/resin-io-modules/resin-token/issues/29

**Comment by emirotin** [comment]
Released in 5.8.0
