### ISSUE TITLE
Resin-cli doesn't support http/https proxies

### ISSUE THREAD

**Issue by nkaul** [resin-io/resin-cli#478]
Resin CLI behind Firewall, doesn't use http, https proxies. 
Upon investigation into firewall logs, its apparent that resin-cli client doesn't use http_proxy and https_proxy settings and tries to connect directly to internet 

# resin --help
ECONNREFUSED: request to https://api.resin.io/whoami failed, reason: connect ECONNREFUSED 54.236.194.208:443

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/resin-io/resin-cli/issues/new
  Forums: https://forums.resin.io

# DEBUG=1 resin --help
Error
    at ClientRequest.<anonymous> (/Users/user-name/.nvm/versions/node/v7.7.3/lib/node_modules/resin-cli/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at emitErrorNT (net.js:1289:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/resin-io/resin-cli/issues/new
  Forums: https://forums.resin.io

**Comment by nkaul** [comment]
Behind enterprise Firewall: From the Firewall logs, it seems that my machine (source ip) is directly trying to connect to destination ip (api.resin.io) without even routing requests through proxy.

I setup a local proxy server(using charles proxy) at home yesterday and was able to confirm again that rein-cli doesn’t go through proxy at all.
The cli client should either have settings to configure http_proxy, https_proxy or pick those up from environment variables of terminal shell from where request is initiated. I believe it should be a relatively easy code fix.
Reference NPM: https://www.npmjs.com/package/https-proxy-agent

**Comment by pimterry** [comment]
Hi @nkaul, thanks for this! To be clear: if you could configure resin-cli to send everything through an HTTP and HTTPS proxy everything would work fine for you, is that right?

Given that, yes, you're entirely right, we don't yet have built in support for proxies. Keep an eye on this ticket and we'll take a look at adding that in soon.

**Comment by emirotin** [comment]
@nkaul the proxy support has been released in 5.9.1. Can you please give it a try and let us know how it works?
