### ISSUE TITLE
Update requests should not happen with every run

### ISSUE THREAD

**Issue by CameronDiver** [resin-io/resin-cli#485]
Currently every run of resin-cli produces this for me:
```


   ╭──────────────────────────────────────╮
   │                                      │
   │   Update available 5.7.1 → 5.7.2     │
   │   Run npm i -g resin-cli to update   │
   │                                      │
   ╰──────────────────────────────────────╯


```
It would be nice if it only did it once for each version or once each few weeks etc.

**Comment by pimterry** [comment]
Interestingly, it used to do that, and we actually do this on purpose instead: https://github.com/resin-io/resin-cli/pull/325.

I kind of agree though - it's annoying when you're using the cli a lot and it keeps coming up. Thoughts @jviotti?

**Comment by jviotti** [comment]
There is an `updateCheckInterval` option for `update-notifier` (https://www.npmjs.com/package/update-notifier)

**Comment by CameronDiver** [comment]
I personally think that it would be better to do it at most once a day, happy to PR this in if everyone is in agreement.

**Comment by jviotti** [comment]
It sounds great to me :+1:

**Comment by pimterry** [comment]
:+1:

**Comment by emirotin** [comment]
@CameronDiver hey still interested doing this?

**Comment by CameronDiver** [comment]
Ah sorry this slipped through the cracks! Yeah I'll do this today. Thanks for reminding me.

**Comment by pimterry** [comment]
Fixed ages ago
