### ISSUE TITLE
Resin quickstart does not work with resinOS2.0

### ISSUE THREAD

**Issue by CameronDiver** [resin-io/resin-cli#533]
I flashed an rpi3 using resin quickstart, the process went fine, except it had written the wifi config to config.json, rather than the newer system_connections/ directory which resinOS2.0 uses, so the device was unable to connect.

**Comment by pimterry** [comment]
Duplicate: https://github.com/resin-io/resin-cli/issues/494

`resin local configure` does work, so you can use that as a workaround, but obviously yes this seriously needs fixing.
