### ISSUE TITLE
resin local configure won't work on resinOS 1.X

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#537]
Currently `resin local configure` only works on devices that have `/resin-boot/system-connections`

**Comment by pimterry** [comment]
We're not going to fix this. If you're using 1.x, you can't run unmanaged images, so you should always be able to use `resin os configure` as a more fully featured alternative, and the `local configure` use case doesn't make sense.

In medium-term we're likely going to be combining these two commands, to simplify things and make this clearer. For now, if you're using Resin OS 1.x, use `resin os configure`.
