### ISSUE TITLE
resin config commands don't work on resinOS 2.0

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#538]
Currently resinOS 2.0 images don't work with some of the `resin config`

relates somewhat to https://github.com/resin-io/resin-cli/issues/537

**Comment by pimterry** [comment]
I'm going to close this. This is true, but the `resin config` commands are all pretty nonsensical for OS 2.x right now, and with #715 we're going to be completely changing how config generation etc works to make them meaningful anyway. I don't think this ticket adds anything beyond that.
