### ISSUE TITLE
TypeError: "cwd" must be a string

### ISSUE THREAD

**Issue by pimterry** [resin-io/resin-cli#543]
https://sentry.io/resinio/cli/issues/285020506/

```
TypeError: "cwd" must be a string
  File "child_process.js", line 380, in normalizeSpawnArguments
  File "child_process.js", line 465, in Object.exports.spawn
  File "/Users/ecto/.nvm/versions/node/v8.0.0/lib/node_modules/resin-cli/node_modules/resin-sync/build/shell.js", line 84, in Object.<anonymous>
    spawn = child_process.spawn(subShellCommand.program, subShellCommand.args, {
  File "/Users/ecto/.nvm/versions/node/v8.0.0/lib/node_modules/resin-cli/node_modules/bluebird/js/release/util.js", line 16, in Object.tryCatcher
    return target.apply(this, arguments);
  File "/Users/ecto/.nvm/versions/node/v8.0.0/lib/node_modules/resin-cli/node_modules/bluebird/js/release/method.js", line 15, in Object.runCommand
    var value = tryCatch(fn).apply(this, arguments);
...
(15 additional frame(s) were not displayed)

TypeError: "cwd" must be a string
```

**Comment by ctartist621** [comment]
Is there a way around this?

**Comment by pimterry** [comment]
@ctartist621 I haven't actually looked into this in depth yet I'm afraid, because I'm not sure exactly how to reproduce it, and it's only just started appearing. Can you reliably reproduce this locally? I'd love to have some more details if so, especially:

* Your node version
* Your resin-cli version
* Whether this happens for any app to try to sync
* Whether this happens for any device you try to sync to
* Whether resin sync has previously been working for you
* Any other unusual details about your environment or process

**Comment by ctartist621** [comment]
@pimterry 

Node: v8.1.0
resin-cli: We started with the most recent, and kept bumping the version back to try and get it to work.  We figured you pushed something that broke it.  We stopped at resin-cli v5.8.0
We only have one app
We only have one device (fresh shop here)
It HAD been previously working with this device...  Probably with a different node version now that I'm thinking of it...
This was on a Mac OSX Sierra computer... latest version I believe.

**Comment by ctartist621** [comment]
@pimterry One note: This pretty much stopped work for the day.  Rescheduling work to accommodate this tomorrow, but it would be great if this was fixed / had a recommendation by the 14th...

**Comment by pimterry** [comment]
@ctartist621 This appears to be a Node 8 issue - I can reproduce this locally on v8.0.0 (on Ubuntu), but it works fine on v6.11.0 (Node LTS), in an otherwise identical environment.

Hopefully that works for you as a workaround in the short-term, I'll do what I can to get a proper fix for Node 8 out next week.

**Comment by gingerschmidt** [comment]
@pimterry Yes, it works fine v6.11.0. Thanks!

**Comment by pimterry** [comment]
This should now be fixed in Node 8 in the latest version of Resin-CLI (6.1.0)
