### ISSUE TITLE
Docker build/deploy return unhelpful error if you don't have docker installed

### ISSUE THREAD

**Issue by pimterry** [resin-io/resin-cli#547]
https://sentry.io/resinio/cli/issues/264667068/

```
Error: connect ENOENT /var/run/docker.sock
  File "util.js", line 1018, in Object.exports._errnoException
  File "util.js", line 1041, in exports._exceptionWithHostPort
  File "net.js", line 1086, in PipeConnectWrap.afterConnect [as oncomplete]

Error: connect ENOENT /var/run/docker.sock
```

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1zk9)

**Comment by Page-** [comment]
Yeah I just hit this in support, the actual user visible error is
```
No such file or directory: undefined
```
which is even more unhelpful than the sentry reported error as it doesn't even hint that docker might be related - it took a long time to figure out the cause

**Comment by imrehg** [comment]
This came up on the forums as well: https://forums.resin.io/t/resin-unattended-deploy/1525/5

**Comment by pimterry** [comment]
In the next CLI release, if the docker socket doesn't exist or is not accessible, this will now fail with:

> Docker seems to be unavailable (using socket #{socketPath}). Is it installed, and do you have permission to talk to it?
