### ISSUE TITLE
resin deploy should gzip the stream before uploading

### ISSUE THREAD

**Issue by CameronDiver** [resin-io/resin-cli#549]
This is a simple fix, just adding a node gzip stream to the outgoing data, and also adding a gzip uncompress stream on the builder side.

**Comment by pimterry** [comment]
@CameronDiver is there an issue for the uncompress side of this in the builder? Very easy to put into the CLI now, but tricky to test if it's working without the other side of it.

**Comment by CameronDiver** [comment]
There is: https://github.com/resin-io/resin-builder/issues/187
