### ISSUE TITLE
NPM install takes a very long time on Git for Windows

### ISSUE THREAD

**Issue by flesler** [resin-io/resin-cli#561]
I'm not sure how long it takes normally, neither if it happens on every single Git for Windows.
In my case, the last 2 times I updated `resin-cli` to a newer version with `npm i -g resin-cli`, it took a very long time.

Just now I checked and it took 11 minutes. Most of the time was spent on `loadRequestedDeps: sill install loadAllDepsIntoIdealTree`

Let me know if you need me to try anything

**Comment by pimterry** [comment]
We made a few improvements to this a while ago, and I think it's got quite a bit better. We're not going to do more though for now, and I'm going to close this, because we're moving away from npm installs entirely, so there's not much value in investing more time in that direction.
