### ISSUE TITLE
device register action failing on OSX

### ISSUE THREAD

**Issue by LucianBuzzo** [resin-io/resin-cli#596]
when running the command `resin device register` on OSX I see the following:

```
ಠ_ಠ (04:52 pm) ~/ resin device register 17202
Registering to Virtuality: 8105ef2de26a7a62efec35fbd3db74cf510d0b7ebb5069a881e0fd2895374a
ResinRequestError: Request error: If the id property is set it must be non-null

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/resin-io/resin-cli/issues/new
  Forums: https://forums.resin.io

ಠ_ಠ (04:52 pm) ~/ resin device register Virtuality
Registering to Virtuality: cbfac3e490bcad6a766434d423b5a41d8dc335f4380e8f15022ac7c1c54f68
ResinRequestError: Request error: If the id property is set it must be non-null

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/resin-io/resin-cli/issues/new
  Forums: https://forums.resin.io

```

**Comment by pimterry** [comment]
No idea why this never got looked into at the time, sorry. I'm assuming @LucianBuzzo you have no idea what was causing this, and no way to reproduce it now?

I can't see any reports of this in our sentry logs (which cover the last 90 days), and we haven't changed the core logic of this code in the CLI for quite a while now, so I suspect this was an api bug. Lots of the logic around provisioning was changing around that kind of time. I'm going to close this for now, but feel free to reopen if you can still reproduce this.
