### ISSUE TITLE
resin local configure should create a new connection file rather than editing `resin-sample`

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#597]
In newer versions of resinOS 2.0, we will be removing or renaming the `resin-sample` file in `/boot/system-connections`. So before we do that, we need to make sure that the CLI can handle this, my suggestion is that the CLI should create a new system connection file in `/boot/system-connections` and not rely on `resin-sample` being there at all.

**Comment by emirotin** [comment]
@shaunmulligan I have some concerns. Right now the CLI does not _own_ this file. I can make an easy fix by moving the ownership here but it will require us to sync any possible changes in the future.
I've read the prior discussion in HQ and I have an alternative proposal. Please let me know if you see any problems with it:

1) I will make the CLI expect the file called `resin-sample.please.rename` and **if it's present** I will first rename it to `resin` (or `resin-connection`) and then populate that file as the CLI is doing now
2) If the file is not there the CLI will keep working with the `resin-sample` as it's doing now
3) When the OS starts shipping this `resin-sample.please.rename` file it can also drop shipping the `resin-sample` at the same time (so basically the OS releases will start shipping the renamed file)

**Comment by emirotin** [comment]
UPD: looks like that's what's already suggested in the OS with a slightly different filename. https://github.com/resin-os/meta-resin/issues/768
So all looks good to me.

**Comment by shaunmulligan** [comment]
@emirotin can we not just have the CLI just add its own connection file. This is what the image maker currently does. So it doesn't need to care in any of the cases if `resin-sample` exists. It will just create something like `resin-wifi` and NM will do the correct thing. 

If it finds a file called `resin-wifi` then it should be able to reconfigure it.

**Comment by emirotin** [comment]
Please see my comment above. Right now the CLI has no specific knowledge about this file. It takes whatever is on the disk and reconfigures it.
Your suggestion also works as I've mentioned in my comment, but it means the knowledge about the file structure will be duplicated in the img-maker and the CLI.
I'm fine with that if you approve, especially if we can extract some shared some code from the img-maker

**Comment by pimterry** [comment]
Sounds like @emirotin is on this, so I've unassigned myself - let me know if I can help here at all though
