### ISSUE TITLE
Support overlay2 in resin local push

### ISSUE THREAD

**Issue by lekkas** [resin-io/resin-cli#599]
Should only require a change in https://github.com/resin-io-modules/resin-sync/blob/master/lib/docker-utils.coffee#L315-L326

Note that `resin sync` is docker FS driver agnostic and overlay2 support should happen on the server side

See: https://www.flowdock.com/app/rulemotion/resin-devices/threads/1wCgvpWvDykVKWxXcfvSWDmpXHe

**Comment by pimterry** [comment]
This is now fixed in resin-sync, and will be fixed for all new CLI installs after the next resin-sync release.
