### ISSUE TITLE
Eventually drop the support for `resin-sample` connection file

### ISSUE THREAD

**Issue by emirotin** [resin-io/resin-cli#602]
See https://github.com/resin-io/resin-cli/blob/master/lib/actions/local/configure.coffee#L161 and https://github.com/resin-io/resin-cli/pull/601#discussion_r129808274

**Comment by pimterry** [comment]
Very shortly this connection config code won't live in the CLI at all, and will be in https://github.com/resin-io-modules/resin-device-init anyway, where it's already been through a few changes en route (and it'll then be moving into reconfix soon-ish too, hopefully). Closing as no longer relevant.
