### ISSUE TITLE
local sync error when parsing docker version

### ISSUE THREAD

**Issue by craig-mulligan** [resin-io/resin-cli#608]
docker version: `17.06.1-ce-rc1`,
resin cli version: `6.3.0`

Occurs during a local sync. 
```
rdt push failed. TypeError: Invalid Version: 17.03.1-ce TypeError: Invalid Version: 17.03.1-ce
    at new SemVer (/usr/local/lib/node_modules/resin-cli/node_modules/semver/semver.js:293:11)
```

**Comment by pimterry** [comment]
Looks like this is the docker version on the target device, not your local docker (since the versions don't match). Which OS version is your device using?

**Comment by pimterry** [comment]
Also, can you run this again with `export DEBUG=1` first? A stack trace would be useful.

I'd normally get it from Sentry, but for some reason this error hasn't turned up in there at all! ...any idea what might be doing that?

Think I've found the fix anyway, watch this space.

**Comment by craig-mulligan** [comment]
Rad @pimterry, let me know if you still need that debugging info.

**Comment by pimterry** [comment]
If it's easy, a proper stack trace would be useful, just to confirm there isn't another issue with this elsewhere that I've missed.
