### ISSUE TITLE
>= 2 word command help doesn't work correctly

### ISSUE THREAD

**Issue by lorenzo-stoakes** [resin-io/resin-cli#62]
So this runs correctly:-

```bash
resin help app
Usage: app <name>

Use this command to show detailed information for a single application.

Examples:

	$ resin app MyApp
```

But if I run `resin help app rm` I get the same output:-

```bash
[~]$ resin help app rm                                                                                   
Usage: app <name>

Use this command to show detailed information for a single application.

Examples:

	$ resin app MyApp
```

Also in both cases I feel it would be useful to have flags like `-y` available and listed here :)

**Comment by jviotti** [comment]
Commands are matched based on order of definition (like a Web Application router entries). This was a specific case were `app` was defined before `app rm`. Other commands, like `resin help device` and `resin help device init` work as expected. Sending a PR in a second..

About the command flags, the are listed in the help pages already :)

```sh
$ ./bin/resin help app rm
Usage: app rm <name>

Use this command to remove a resin.io application.

Notice this command asks for confirmation interactively.
You can avoid this by passing the `--yes` boolean option.

Examples:

        $ resin app rm MyApp
        $ resin app rm MyApp --yes

Options:

    --yes, -y   confirm non interactively
```
