### ISSUE TITLE
resin configure: You don't have enough privileges to run this operation. 

### ISSUE THREAD

**Issue by bitmarker** [resin-io/resin-cli#652]
Hello guys,
I'm executing the command with sudo, but still getting the error (on macOS):

➜  ~ resin local configure ~/Downloads/resin.img
You don't have enough privileges to run this operation.
Try running this command again prefixing it with `sudo`.

If this is not the case, and you're trying to burn an SDCard, check that the write lock is not set.

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/resin-io/resin-cli/issues/new
  Forums: https://forums.resin.io

**Comment by pimterry** [comment]
Hi @bitmarker, that's an odd one. That message means somewhere a `EPERM` error is being thrown, but doesn't give us much more information than that. It's definitely not usual to hit that error after you've used `sudo`. A few questions:

* What version of node & the CLI are you using?
* What are the permissions on that image?
* Do you see any additional output if you run `export DEBUG=1` before running this command?
* Anything else unusual about your setup?

**Comment by pimterry** [comment]
Closing this for now, feel free to reopen with the info if you're still seeing this.
