### ISSUE TITLE
`resin os download` incomplete

### ISSUE THREAD

**Issue by mdtusz** [resin-io/resin-cli#661]
- **resin-cli version: 6.6.6**
- **Operating system and architecture: OSX 10.11.6 - x86-64**

When running `resin os download raspberrypi3 -o resin-rpi3.img`, I would expect the full image to be downloaded for use on devices, but the resulting file is only 48K and very clearly not the correct resin-os image.

```
myDir|master⚡ ⇒ resin os download raspberrypi3 -o test.img
Getting device operating system for raspberrypi3
OS version is not specified, using the default version: the newest stable (non-pre-release) version if available, or the newest version otherwise (if all existing versions for the given device type are pre-release).
The image was downloaded successfully
myDir|master⚡ ⇒ ls -lh test.img
-rw-r--r--  1 me    staff    48K Sep 19 15:43 test.img
```

**Comment by pimterry** [comment]
I think this is the same issue as https://github.com/resin-io/resin-cli/issues/541 - failed downloads get cached, breaking download for that specific device type & version in future. Can you delete `~/.resin/cache` completely, and try again?

**Comment by mdtusz** [comment]
Ahhh yep! That seems to solve the issue and the download succeeds. Closing in favour of #541.
