### ISSUE TITLE
Local push should use a default container name automatically

### ISSUE THREAD

**Issue by pimterry** [resin-io/resin-cli#682]
Right now, local push prompts you for a Docker container name, which is messy (#519) and bug-prone (#545), lets users get into odd states (multiple locally pushed applications running at the same time) and doesn't really give users any particular benefit.

Unless there's a good reason for this (@lekkas, @CameronDiver, @shaunmulligan?) we could just automatically use a single fixed name (e.g. `local-app`) instead. That would let us easily fix this, simplify the code, remove some bugs and improve local push UX in one easy swipe.

**Comment by shaunmulligan** [comment]
@pimterry how will this work in multicontainer? I'm all for doing this, but would be good to have a plan for multicontainer. Perhaps we could add a docker LABEL to the containers started by the CLI?

**Comment by pimterry** [comment]
@shaunmulligan That would work. I'd kind of like to just get this quick fix in right now regardless though, since it caused a fair amount of pain at the hackathon, we're not aiming to have multicontainer local push working immediately anyway, and it's an _extremely_ easy fix 1 line fix we can safely add in the short term.

With multicontainer though, you're right we can't have a single container name of course. We could extend this to generate a fixed name per service though (say, `local-app-<service-name>`), plus use some unique CLI label to make them easier to find for cleanup before each push.

**Comment by lekkas** [comment]
@pimterry I don't have any objections on this nor do I remember the context/reasons why we wanted users to specify a container name in the first place. +1 on simplifying the workflow.

**Comment by pimterry** [comment]
This has now been fixed in resin-sync 9.2.4, which should get picked up by all future CLI installs.

For now it just uses the default `local-app` name - we can look at how this will work for multicontainer as we start redesigning the CLI for that soon, but there's a few good options, and I don't think we need to decide quite yet.
