### ISSUE TITLE
Support `resin config generate` in a non-interactive mode

### ISSUE THREAD

**Issue by jviotti** [resin-io/resin-cli#695]
Requested by a user on support. They'd like to pass the options that command asks for as arguments, so they can more easily script its operation.

**Comment by pimterry** [comment]
@jviotti can you link the specific Front thread here, for the full context? Probably want to tag that thread with this issue too, so we can track it properly.

**Comment by jviotti** [comment]
I linked the Front thread to this ticket already, but didn't paste the Front link here as I thought we only wanted to do so in private repos. This is the thread: https://app.frontapp.com/open/cnv_982ssp

**Comment by pimterry** [comment]
Yeah, it's suboptimal in public repos since they're not useful externally, but it's definitely useful for resin people for context, and front links aren't secret. Thanks!

**Comment by pimterry** [comment]
Fixed and released in 6.9.0
