### ISSUE TITLE
After successful login won't let me run commands

### ISSUE THREAD

**Issue by craig-mulligan** [resin-io/resin-cli#71]
Hi I'm logging in successfully but then it says I can't run any commands cause I am not logged in. 

Successfully logged in as: craig
➜  ~  resin drives
You have to log in

**Comment by jviotti** [comment]
@craig-mulligan There was a hot fix for this issue: https://github.com/resin-io/resin-cli/commit/7e5ecd634dae409892e04f49eedb6a3062a04734. Make sure you're running `v0.11.1`.
