### ISSUE TITLE
sudo resin local promote 10.10.10.24 fails with unknown command

### ISSUE THREAD

**Issue by SvenDowideit** [resin-io/resin-cli#710]
- **resin-cli version: 6.8.0**
- **linux amd64 talking to rpi Resinos2.3.0-dev**

```
sven@y260:~/src/resin-go-hello-world$ sudo resin local promote 10.10.10.24
Error: unknown command "interactive" for "resin-provison"
Run 'resin-provison --help' for usage.
2017/11/07 08:25:15 unknown command "interactive" for "resin-provison"
Connection to 10.10.10.24 closed.
```

this is a resin host that was previously part of an application, but somehow has lost its marbles, so IDK :)

**Comment by pimterry** [comment]
@SvenDowideit that's unusual, and I've certainly not seen that before. Can you reproduce this with a fresh device, that hasn't "lost it's marbles"? :smiley:

Also, are you use the error message above is accurate? `provison` doesn't appear anywhere in our source, so far as I can tell, and promote definitely tries to run `resin-provision`:

https://github.com/resin-io/resin-cli/blob/master/lib/actions/local/promote.coffee#L65-L73

**Comment by SvenDowideit** [comment]
yes, I'm pretty sure I copy and pasted - but lets see what else we can find out.

the hard part atm, is scouring the house for sd cards to try :)

**Comment by SvenDowideit** [comment]
yes, it continues to be weird. on this new sdcard, on a different rpi:

```
sven@y260:~/src/resin-go-hello-world$ sudo resin version
6.8.0
sven@y260:~/src/resin-go-hello-world$ 
sven@y260:~/src/resin-go-hello-world$ 
sven@y260:~/src/resin-go-hello-world$ 
sven@y260:~/src/resin-go-hello-world$ sudo resin local promote 10.10.10.127
[sudo] password for sven: 
Error: unknown command "interactive" for "resin-provison"
Run 'resin-provison --help' for usage.
2017/11/09 05:06:40 unknown command "interactive" for "resin-provison"
Connection to 10.10.10.127 closed.
sven@y260:~/src/resin-go-hello-world$ sudo resin local scan
Reporting scan results
- 
  host:          1a7a2af.local
  address:       10.10.10.24
  dockerInfo: 
    Containers:        2
    ContainersRunning: 2
    ContainersPaused:  0
    ContainersStopped: 0
    Images:            3
    Driver:            aufs
    SystemTime:        2017-11-09T05:06:55.105404366Z
    KernelVersion:     4.4.50
    OperatingSystem:   Resin OS 2.3.0+rev1
    Architecture:      armv7l
  dockerVersion: 
    Version:    17.03.1-ce
    ApiVersion: 1.27
sven@y260:~/src/resin-go-hello-world$ sudo resin local --help
Command not found: local

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/resin-io/resin-cli/issues/new
  Forums: https://forums.resin.io

sven@y260:~/src/resin-go-hello-world$ sudo resin local ssh 10.10.10.127
? Select a container /jovial_engelbart (fde42911836) - Up 29 minutes
root@7567a94:/go/src/github.com/resin-io-projects/resin-go-hello-world# uptime 
 05:07:46 up 38 min,  0 users,  load average: 0.03, 0.06, 0.17
root@7567a94:/go/src/github.com/resin-io-projects/resin-go-hello-world# 
```

**Comment by pimterry** [comment]
We've had some internal discussion about this: right now `resin provision` doesn't work, and we're in the process of doing some larger changes to ResinOS itself to make this entire unmanaged -> managed flow for users work far more effectively.

What that means in practice is that this is 'expected' - we don't actually support the current implementation, we haven't actively advertised it, and we shouldn't really have released the command in the CLI in the first place given that. Sorry for the confusion! I'm going to remove the command entirely, and then close this ticket.

(internal flowdock link for context: https://www.flowdock.com/app/rulemotion/r-resinos/threads/ekN_XdiSQLNbIDiYJzf7qevPPwO)

**Comment by pimterry** [comment]
Removed entirely in 6.8.3.
