### ISSUE TITLE
resin CLI seems to delete itself after trying to perform an update

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#72]
When i ran "resin apps" the cli said it was performing a minor update, this failed and now when i run resin apps, it says command not found.

here is the console log:
```
resin-io:resin-ftp hobochild$ resin whoami
shaun
resin-io:resin-ftp hobochild$ resin apps
Performing patch update, hold tight...
Command failed: /bin/sh -c npm install --silent --global resin-cli

resin-io:resin-ftp hobochild$ sudo resin apps
Password:
sudo: resin: command not found
resin-io:resin-ftp hobochild$ resin apps
-bash: /usr/local/bin/resin: No such file or directory
resin-io:resin-ftp hobochild$ which resin 
resin-io:resin-ftp hobochild$ 
```

**Comment by jviotti** [comment]
This is an issue with NPM. In case of an installation error, they should automatically rollback to the previously installed version, which they don't.

As an improvement, the CLI will no longer perform a self update, and will instead notify the user to run the update command by his own: https://github.com/resin-io/resin-cli/issues/72.

**Comment by jviotti** [comment]
Let's discuss this again if prevent the self update still confuses users. In that case we could add an informative message to `resin update` explaining the possible problem caused by NPM.
