### ISSUE TITLE
Any plans to support pushing code/container binaries using usb instead of network?

### ISSUE THREAD

**Issue by iSsO** [resin-io/resin-cli#735]
I'm aware of the complexity of the resinio/resinos platform, but I wasn't sure where to ask for this. As it affects multiple repos.

I was wondering, are there any plans to support uploading code/container binaries using usb with `local push` command?

I think it will help a lot while developing, it the board has a usb device socket and connected to the dev machine.

**Comment by pimterry** [comment]
@iSsO which board would you like to do this with?

To support this, we'd have to have a way to communicate with the Docker engine on the device over USB, or at least with some other service that could communicate to Docker for us.

For a few devices (e.g. a pi 3) that's impossible - the microusb connection has only the power pins physically connected, so there's no way we can communicate. Sadly, there's nothing we can do directly there.

For others, like the pi zero, this is possible in principle. The easiest way is to connect the device to a host with USB acting as a network between them, see https://learn.adafruit.com/turning-your-raspberry-pi-zero-into-a-usb-gadget/ethernet-gadget for a walkthrough of that in general. I've never tried it myself, but it doesn't look too bad. If you set that up, then the current `local push` setup should work straight away. As soon as you have a network between the devices, you should be able to push to the ip or hostname of the USB device straight away, and in principle everything should work perfectly.

**Comment by iSsO** [comment]
@pimterry My plan is to do a custom board based on the new PocketBeagle from BeagleBone or something similar. So the microusb connection is not an issue, I'll make sure it is connected to the port and interfaced correctly. (It is already connected to the host in case of PocketBeagle BTW)

Emulating a network device using the board's microusb seems like an interesting idea. It is clean and it shouldn't affect the software side.

Thanks Tim

**Comment by pimterry** [comment]
Neat, that sounds awesome. Let us know how it goes!

**Comment by iSsO** [comment]
I will let you know the updates. :)

I have another question, do you think that service that emulates the network device should be running in the host os or my app container? 

I know that the cli updates the running container, but does it handles updates to the host os as well? and if it doesn't, can you suggest how can it be achieved if I have the resinos binaries compiled for my board?

**Comment by pimterry** [comment]
@iSsO in general, I'd run almost everything through a container, rather than the OS. Independent of everything else, it'll simpler be much easier to manage there.

The CLI doesn't manage updates to the host OS right now, no. We mostly do host updates through resin.io itself - I'm not actually sure what the expected process is for unmanaged resinos devices, especially for a custom board, but @imrehg might have some thoughts.

**Comment by iSsO** [comment]
Thanks Tim, is it planned for the CLI to do host OS upgrades in the future?

@imrehg I would love to know your thoughts on the host OS upgrade options for unmanaged resinos devices.

**Comment by imrehg** [comment]
@iSsO there's a lot of work going into hostOS updates recently, and there are some functionality coming in hopefully soon that will make things easier, and could make cli-based host updates more likely too.

Currently the update functionality works within resin.io (the managed service), and could probably work outside for the device types that are supported for updates currently, but for a custom board that would not cut it just yet. We are discussing it internally, though, how to best add that to unmanaged devices. Custom boards add extra complexity as well (mainly for the boot-related setup, most boards differ from each other regarding the boot infrastructure, even though the rootfs is pretty much the same), and might require some work on the custom board's developer's side to add everything needed to the resinOS setup.

If you make a custom board, then make sure that you are building on top of the latest meta-resin (2.9.0+ at the moment), on the update side that should set most of the things up, so when you'll have a working device, the hostOS update might be relatively simple as running a single command on the device

**Comment by pimterry** [comment]
As an aside, I think we're getting a bit outside the scope of the CLI here @iSsO, and we try to focus this repo on specific bug reports/feature requests. If you'd like to discuss this further, or anything else, feel free to start a thread on the forums: https://forums.resin.io.

**Comment by iSsO** [comment]
Got it!, thanks guys.
