### ISSUE TITLE
Get SD card writing progress in minutes instead of seconds

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#75]
Currently the SD card writing progress is imported in seconds,
`Writing Device OS [=======                 ] 29% eta 531s`
but it may be more user friendly to report this in minutes instead.

**Comment by Page-** [comment]
I'd say a mix, eg `8m51s`

**Comment by jviotti** [comment]
@Page- +1.

**Comment by jviotti** [comment]
This is being implemented in Resin CLI Visuals: https://github.com/resin-io/resin-cli-visuals/pull/13.

**Comment by jviotti** [comment]
Implemented and rebased to quick start branch.
