### ISSUE TITLE
Allow logging in with API keys that don't expire

### ISSUE THREAD

**Issue by thgreasi** [resin-io/resin-cli#752]
HQ: https://github.com/resin-io/hq/pull/861

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6dv5)

**Comment by pimterry** [comment]
Effectively fixed by https://github.com/resin-io/resin-cli/pull/835 (v7.2.0). Not all commands are supported yet, but the key ones for CI are (build, deploy) and all commands will be automatically supported once we move fully to the MC SDK, finishing #663.

**Comment by pimterry** [comment]
Most commands don't work. `devices` and `apps` won't, for example. The main use case for api keys seems to be in CI builds, which tend to just run `build` and `deploy`, and those work great.

We will have full support everywhere eventually effectively for free as part of other changes. In the meantime, if there are any particular commands where it'd be useful to get support ASAP, we can definitely do that, just let me know.

**Comment by lekkas** [comment]
Thanks @pimterry , I've updated the user and will keep an eye for any high prio requests to support other commands.
