### ISSUE TITLE
Incorrect device instructions after device init.

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#76]
The physical instructions shown to the user after burning process are incorrect as they are the same instructions from the dashboard, talking about using `dd` etc.  This needs to be fixed in the device-type spec

**Comment by jviotti** [comment]
I confirm that this needs to be addressed within device specs, so we can't take action for now.

**Comment by jviotti** [comment]
Instructions are not being shown anymore, so this issue is now irrelevant.
