### ISSUE TITLE
Resin local SSH does not support balena based devices

### ISSUE THREAD

**Issue by CameronDiver** [resin-io/resin-cli#761]
Using `resin ssh` with balena based devices gives the following error:
```
eporting discovered devices
? select a device edbc4e4.local (192.168.0.112)
? Select a container /local-app (8a72d0a348b) - Up 31 minutes
sh: docker: command not found
Connection to 192.168.0.112 closed.
```
- v 6.12.5

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6v4p)

**Comment by mdtusz** [comment]
This seems to also affect `resin local push` - or at least is for me.

**Comment by pimterry** [comment]
@mdtusz could you provide more information? I've now got a fix for local ssh available (https://github.com/resin-io/resin-cli/pull/777), but I can't find anywhere in local push that we depend on the binary name, and I've just run a test locally with a 2.9.6 device (so using Balena) and it works fine. What exactly are you running, and what output are you seeing?

**Comment by pimterry** [comment]
Closing for now, since the local ssh issue is resolved - feel free to open an issue for `local push` though @mdtusz if you have any more details.
