### ISSUE TITLE
Allow injecting config into images, not just drives

### ISSUE THREAD

**Issue by pimterry** [resin-io/resin-cli#762]
`resin config inject` only supports drives, and does not allow you to inject directly into an image.

**Comment by jhermsmeier** [comment]
@pimterry fyi, this already appears to work just fine when specifying an image with the `--drive` flag, although there is #784 which is a bit counter-intuitive

**Comment by pimterry** [comment]
Ah, this was a documentation bug, which has now been fixed: https://github.com/resin-io/resin-cli/pull/767

That sounds fine, I'll close this (and we can look at the other issues separately later)
