### ISSUE TITLE
CLI should build on npm 5

### ISSUE THREAD

**Issue by lekkas** [resin-io/resin-cli#765]
We require npm4 for the build process and it is stated nowhere in the README. It's implied with the `require-npm4-to-publish` script/dependency but it's easy to miss because the prepublish script is not invoked when building the cli locally. 

see: https://www.flowdock.com/app/rulemotion/public-s-community/threads/PtlnyJqSUPmiRZdNC8oUKUNFOFU

- **resin-cli version: all**
- **Operating system and architecture:**

**Comment by lekkas** [comment]
Marked as bug because this is slowing down contributors who want to perform trivial changes like cli doc updates.

**Comment by pimterry** [comment]
@lekkas can you confirm that the current master with a fresh npm install now builds for you locally? If so, I think we can close this.

**Comment by lekkas** [comment]
On it

**Comment by lekkas** [comment]
@pimterry `npm run build` is now working flawlessly on my machine
