### ISSUE TITLE
resin devices still shows old format dashboard link

### ISSUE THREAD

**Issue by imrehg** [resin-io/resin-cli#768]
- **resin-cli version:** 6.12.5
- **Operating system and architecture:** Linux 64bit (Arch)

The output of the `DASHBOARD URL` column is as `https://dashboard.resin.io/apps/506266/devices/999586/summary` instead of the new format of `https://dashboard.resin.io/devices/0e7e4adb2edfec6b8cd5bbfc72a8804c/summary`

**Comment by thgreasi** [comment]
Updating the sdk to v8 should fix that.
