### ISSUE TITLE
Proposal: present a link to the application dashboard while user waits for Download.

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#77]
It may be nice to present a link in the quickStart CLI which points to the dashboard of the application they are working on, so they can see that the device is in the "connecting.." state on the dashboard. This will allow them to explore the dashboard while they wait for OS download. However, this needs to be thought about in the context of the full user flow and make sure it makes sense.

**Comment by jviotti** [comment]
Closing as unnecessary for now.
