### ISSUE TITLE
resin login does not return to shell after authentication

### ISSUE THREAD

**Issue by lekkas** [resin-io/resin-cli#791]
- **resin-cli version: 6.13.0**
- **Operating system and architecture: macOS 10.12.6**

```
Logging in to resin.io
? How would you like to login? Web authorization (recommended)
Connecting to the web dashboard
Successfully logged in as: [username]

Find out about the available commands by running:

  $ resin help

If you need help, or just want to say hi, don't hesitate in reaching out at:

  GitHub: https://github.com/resin-io/resin-cli/issues/new
  Forums: https://forums.resin.io
```

**Comment by pimterry** [comment]
Ah, interesting. You're saying it runs, outputs all the above, and then just stops there? That's not great. A few questions:

* Does this happen reproducibly every time?
* Are you using the npm or standalone version?

**Comment by lekkas** [comment]
> Does this happen reproducibly every time?

Yeap, it has also reported by other users cc @curcuz 

> Are you using the npm or standalone version?

I'm using the npm version

**Comment by pimterry** [comment]
It definitely doesn't do this on my (Linux) machine, so it's interesting that it's totally reproducible elsewhere. Does it change anything if you are/aren't already logged in beforehand?

Have we seen this anywhere that wasn't OSX? I suspect this might be something platform specific... I'll hunt down my macbook and see if I can reproduce.

**Comment by lekkas** [comment]
I've only seen this in OSX - thanks for hunting this down!

**Comment by pimterry** [comment]
Tested, I can reproduce this on OSX.

**Comment by pimterry** [comment]
I'm pretty sure this is fixed, but if you've got a sec @lekkas it'd be great if you could do a quick check with the latest published CLI to confirm.

**Comment by lekkas** [comment]
Confirmed it is fixed @pimterry 👌
