### ISSUE TITLE
Can't install using npm

### ISSUE THREAD

**Issue by OdysLam** [resin-io/resin-cli#797]
- **resin-cli version:** latest
- **Operating system and architecture:** macOS Hight Sierra

I have npm 5.6 and node 9.5, can't install resin-cli due to multiple deprecated warnings.

I have tried multiple solutions but to no avail, any ideas?

Thank you for your time

```
npm install --global --production resin-cli
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
/Users/Odys/.npm-packages/bin/resin -> /Users/Odys/.npm-packages/lib/node_modules/resin-cli/bin/resin
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: diskpart@1.0.2 (node_modules/resin-cli/node_modules/diskpart):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for diskpart@1.0.2: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: removedrive@1.1.2 (node_modules/resin-cli/node_modules/removedrive):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for removedrive@1.1.2: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})

+ resin-cli@6.13.4
added 4 packages and updated 1 package in 48.659s
```

**Comment by lekkas** [comment]
Hi @OdysLam ,

`resin-cli` *should* be installed anyway, regardless of the warnings. Does`$ resin version` yield any results?

In any case, we should look into deprecated dependencies since these warnings can (and do) cause confusion.

**Comment by OdysLam** [comment]
Either resin is not installed or not linked because it says "Command not found"

**Comment by lekkas** [comment]
@OdysLam my guess is that the folder of globally installed npm scripts is missing from your `$PATH` , which could happen depending on how you installed `npm`.

Normally, the resulting folder from `echo $(npm config --global get prefix)/bin` should appear in `$PATH`. If it does not, a quick workaround would be to append this folder in the `$PATH` variable in your `~/.bashrc`. A second option would be to attempt an npm reinstall (By the way, how do you install `npm` in the first place?). Another alternative is to try using our standalone CLI binary [by following these installation instructions.](https://github.com/resin-io/resin-cli#standalone-install)

**Comment by OdysLam** [comment]
I had a huge problem with a nextclick-args bug  and eventually re-installed node using the provided .pkg from their site.

The USER/.npm-packages does not appear in the $PATH, that's strange since I suppose that the .pkg is the official way of installing node/npm (and not brew).

**Comment by pimterry** [comment]
@OdysLam It sounds like from the above, this is a configuration issue on your system, not a CLI bug, is that right? You'll definitely need the npm bin path in your `$PATH` to install packages like resin CLI.

I'm going to close this bug report for now, since it doesn't look like a CLI bug, but feel free to ping here if you are still having trouble.
