### ISSUE TITLE
Proposal: suggest/show default file directory for code

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#81]
When the quick start asks the user to select a directory that they want to associate to the app, it would be nice if the prompt would show a default or suggested file location, so the user could just hit enter and the default would be used.
e.g.:
`$ Please select a directory (~/Resin_projects/myAppName):    `

**Comment by jviotti** [comment]
Closing as duplicated of https://github.com/resin-io/resin-cli/issues/91.
