### ISSUE TITLE
Install fails with npm on macOS

### ISSUE THREAD

**Issue by mdtusz** [resin-io/resin-cli#810]
- **resin-cli version: latest (v7.0.2)**
- **Operating system and architecture: macOS 10.13.3**

Installing the latest version fails:

### Reproduction

Starting from fresh (i.e. after `npm uninstall -g resin-cli)

```
$ npm i -g --production resin-cl
```

### Output:

```
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: removedrive@1.1.2 (node_modules/resin-cli/node_modules/removedrive):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for removedrive@1.1.2: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})

npm ERR! path /usr/local/lib/node_modules/resin-cli/node_modules/resin-cli-visuals/node_modules/drivelist/scripts/darwin.sh
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/resin-cli/node_modules/resin-cli-visuals/node_modules/drivelist/scripts/darwin.sh'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/miklos/.npm/_logs/2018-03-13T18_34_06_037Z-debug.log
```

Seems to be an issue in `drivelist` where it is still trying to use `darwin.sh` despite it being removed:
https://github.com/resin-io-modules/drivelist/blob/6e4a432b8cc011db227842df2e008f31dc1669d6/package.json#L35

**Comment by mdtusz** [comment]
Also note - this breaks installs of previous versions as well as the version of `drivelist` is not pinned.

**Comment by mdtusz** [comment]
Seems to be fixed in `drivelist` here: https://github.com/resin-io-modules/drivelist/commit/4d6296c165bf7db2050721c02e096e6245d3b0c6

Thanks @jhermsmeier

**Comment by jhermsmeier** [comment]
@mdtusz yeah, sorry about that one!
Ref PR https://github.com/resin-io-modules/drivelist/pull/256
