### ISSUE TITLE
Login into Resin OS

### ISSUE THREAD

**Issue by Davidnet** [resin-io/resin-cli#826]
It will be possible to login from host to the resin os?

Thanks

**Comment by pimterry** [comment]
Hi @Davidnet, I'm not totally sure what that means.

This sounds more like a general question than a specific bug or feature request. This issue tracker is for concrete bugs/feature requests for the CLI itself - would you mind posting this on [the forums](https://forums.resin.io/) instead? The community & the engineering team are very happy to chat there about ideas or any problems you might have.

(Of course, if I've misunderstood and this is indeed a CLI bug, just let me know and we can investigate further!)
