### ISSUE TITLE
Improve flow for associating folder in quickStart.

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#83]
Is there a way we can improve or make clearer what is happening when quickstart asks to associate a folder to the app, it is unclear what format the input requires. Also its unclear if it is relative to root or the current working directory. I have associated my whole Desktop once or twice by mistake :smile:

**Comment by jviotti** [comment]
The command currently prints:

```sh
Are you sure you want to associate /my/current/directory with MyApp? (y/N)
```

Is this enough to make it clean what directory is going to be associated?

Alternatively, would extending the current command help section solve the issue (not sure how many people look at those though)?

```sh
$ resin help app associate
Usage: app associate <name>

Use this command to associate a project directory with a resin application.

This command adds a 'resin' git remote to the directory and runs git init if necessary.

Notice this command asks for confirmation interactively.
You can avoid this by passing the `--yes` boolean option.

Examples:

        $ resin app associate MyApp

Options:

    --yes, -y   confirm non interactively
```

**Comment by jviotti** [comment]
Closing as solved, given the confirmation message.
