### ISSUE TITLE
The CLI should be able to trigger builds on resin's build server infrastructure

### ISSUE THREAD

**Issue by CameronDiver** [resin-io/resin-cli#843]
Essentially, using the CLI, a user should be able to forgo the entire git push workflow, aiding development - especially for windows users.

HQ: https://github.com/resin-io/hq/issues/265

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_b33f)

**Comment by lvaylet** [comment]
I got redirected to this issue following [a post on the forum](https://forums.resin.io/t/multicontainer-and-multiple-repos/2924) and I am having a hard time figuring out the relationship. Could you elaborate a bit on how this feature is supposed to help? Are you planning to give us full control over the command that is executed on resin's build servers?

**Comment by CameronDiver** [comment]
Hey @lvaylet I'd expect the way that this solves the issue that you're having would be that you can explicitly clone your submodules before a `resin push`, e.g.

```
git clone myrepo --recurse-submodules
cd myrepo
resin push myapp
`

This would ensure that all of your submodules are deployed correctly.

**Comment by lvaylet** [comment]
That would be amazing indeed. Looking forward to it!

**Comment by cdgraff** [comment]
+1

**Comment by CameronDiver** [comment]
Forgot to close the issue, implemented with https://github.com/resin-io/resin-cli/pull/868.
