### ISSUE TITLE
Logs not updating in dashboard (restart needed)

### ISSUE THREAD

**Issue by ionita-sonah** [resin-io/resin-cli#864]
Hi, I am experiencing a dashboard-related issue. 

Background: I am currently working on a multi-container application. 

After pushing new code, I notice that the Logs widget is either very slow or it just freezes. I end up restarting the application to get up-to-date logs. Immediately after hitting restart I see a lot of (apparently buffered) lines flushing in. Is it just the internet connection from the git repository to the resin.io server or a known issue?

**Comment by ionita-sonah** [comment]
I now noticed I posted this in the resin-cli respository. Any better suggestions?

**Comment by ionita-sonah** [comment]
I posted this also in the forum: 
https://forums.resin.io/t/logs-not-updating-in-dashboard-restart-needed/2955

**Comment by pimterry** [comment]
Hi @ionita-sonah! That's not a known issue, certainly. The forums are indeed the right place to go with this, so I'm going to close this here, as it's not CLI related. I'll nudge some people to take a look though.
