### ISSUE TITLE
Doesn't seem to validate user right at the start of the command

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#87]
Doesn't ask to select an application anymore??? this was due to not being logged in, but it let me get all the way to selecting device type before telling me i needed to be logged in. ( Later discovered I was actually logged in a production account, but endpoint was staging)

**Comment by jviotti** [comment]
The current `user` permission checks that there is a saved token, but doesn't check the validity of the token itself. This would be fixed by requesting `/whoami` in the permission declaration.

**Comment by jviotti** [comment]
This issue was addressed in the following SDK PR: https://github.com/resin-io/resin-sdk/pull/122.
