### ISSUE TITLE
Cannot use resin sync [spawn error]

### ISSUE THREAD

**Issue by cSchubes** [resin-io/resin-cli#890]
- **resin-cli version:**
7.5.1
- **Operating system and architecture:**
Workstation: Ubuntu 16.04 x86_64
Resin device: BeagleBone Black, armv7hf with ResinOS

**Issue**
Previously used `resin sync` without any issues. Today I get this error everytime I run it:
```
Getting information for device: <uuid>
Got application container info.
Synced /usr/src/app on <uuid>
Application container started after failed 'sync'.
resin sync failed. Error: spawn /bin/sh ENOENT
No such file or directory: /bin/sh
```
I can't seem to get around this no matter what I do. I've checked on both devices, and they both definitely have /bin/sh. Is this a node issue?

**Comment by pimterry** [comment]
@cSchubes Hmm, that's very unusual. Do you have `/bin/sh` available and accessible on _your_ machine? That's where this is being run.

You'll also need `rsync` and `ssh` available in your PATH, are they present? It's possible that that's what this error is referring to, and it's just confusingly reported.
