### ISSUE TITLE
resin-cli ssh - undefined symbol: ext2fs_open_file

### ISSUE THREAD

**Issue by Griffin38** [resin-io/resin-cli#891]
- **resin-cli version:**
resin-cli-7.5.1-1 and resin-cli-7.5.0-1  

- **Operating system and architecture:**
Arch-Linux x86

Behavior:
  When trying to ssh into a device, i get the following error message
```/usr/lib/node_modules/resin-cli/node_modules/ext2fs/build/Release/bindings.node: undefined symbol: ext2fs_open_file

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/resin-io/resin-cli/issues/new
  Forums: https://forums.resin.io 
```

The following commands all crash with the same error message and nothing else
`sudo resin local ssh <UUID>`
`sudo resin ssh <UUID>`
`resin --verbose ssh`
`resin ssh`

I was unsure if I should have created this ticket on https://github.com/resin-io/node-ext2fs , but since it was a error on the resin-cli I decided to post it here.

Thanks

**Comment by zvin** [comment]
@Griffin38 how did you installed resin-cli and which node version are you using?

**Comment by Griffin38** [comment]
I'm using node version v10.4.0

I've installed resin-cli from AUR (arch's community repo). `pacaur -S resin-cli`. You can see the pkginfo on https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=resin-cli .

**Comment by zvin** [comment]
@Griffin38 do you still have this issue?
I just used `PKGBUILD` from the https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=resin-cli in an Arch VM with `makepkg -si` and it built and installed a usable `resin-cli`.
I can `resin ssh` with it.

**Comment by Griffin38** [comment]
No i got it fixed
