### ISSUE TITLE
Local push is launching cached / old application version

### ISSUE THREAD

**Issue by zrzka** [resin-io/resin-cli#914]
## Version

* resin-cli 7.6.2
* macOS 10.13.5 (17F77)
* Raspberry Pi 3 B+ device

## Description

* I made first resin tests with [resin-rust-hello-world](https://github.com/resin-io-projects/resin-rust-hello-world), deployed as `local-app` (app name)
* Then I created my application [rust-thermometer](https://github.com/zrzka/rust-thermometer) and deployed it as `local-rust-thermometer` (app name)
* Based on [this comment](https://github.com/resin-io/resin-cli/issues/757#issuecomment-401340055) and [#912](https://github.com/resin-io/resin-cli/issues/912) I trashed `.resin-sync.yml` and removed `--app-name`, so `local-app` (app name) will be used
* Deployed via [local-push.sh](https://github.com/zrzka/rust-thermometer/blob/master/scripts/local-push.sh) script & [resin-sync.yml](https://github.com/zrzka/rust-thermometer/blob/master/resin-sync.yml)

No matter what I do, it launches cached hello world example (I see _Hello, world!_) in logs ...

```
Current default time zone: 'Etc/UTC'
Local time is now:      Mon Jul  2 06:32:07 UTC 2018.
Universal Time is now:  Mon Jul  2 06:32:07 UTC 2018.

Hello, world!          <--------
sudo: unable to resolve host 3a2bbb8
xinit: connection to X server lost
```

... and it completely ignores my thermometer. When I ssh into container ...

```bash
root@3a2bbb8:/usr/src/app# ls src/
app  config.rs	error.rs  log.rs  main.rs  processing  state.rs  w1
root@3a2bbb8:/usr/src/app# cat src/main.rs
extern crate chrono;
extern crate clap;
extern crate find_folder;
extern crate futures;
#[macro_use]
extern crate lazy_static;
extern crate piston_window;
#[macro_use]
extern crate slog;
extern crate slog_async;
extern crate slog_term;
extern crate tokio;
extern crate tokio_codec;
extern crate tokio_fs;
extern crate tokio_timer;

mod app;
mod config;
mod error;
mod log;
mod processing;
mod state;
mod w1;

fn main() {
    let logger = log::create_root_logger();
    let shared_state = state::SharedState::new();

    info!(logger, "Spawning background thread for processing");
    processing::spawn_background_thread(shared_state.clone(), logger.clone());

    // TODO: Add some shutdown logic (SIGTERM), especially for Docker image on resinOS
    info!(logger, "Launching UI");
    app::run(shared_state);
}
root@3a2bbb8:/usr/src/app#
```

... it contains correct app source code, there's no `println!("Hello, world!")`, etc.

SSHed into the device and removed all images via `balena`. Pushed locally again and _Hello, world!_.

Decided to try again with `--app-name local-rust-thermometer`, pushed locally and _Hello, world!_.

I thought, okay, I probably messed the device completely (forgot to enable local mode, ...) and I decided to remove it from my fleet, flash it and add it again. To my surprise, still _Hello, world!_. There's caching involved somehow where even `--force-build` doesn't help.

Is there a way how to really force rebuild of everything? Ignore caches? Still investigating, maybe you already saw something like this and there's an easy fix for this.

**Comment by pimterry** [comment]
There isn't any caching in the CLI that I can think of that could cause anything like this I'm afraid. All the CLI does for local push is connect to the Docker server on the target device, tar & upload your source files, and ask it to build them. If you've replaced the device, you've replaced all the build state. I can't really think of anything in the CLI that could cause this, other than somehow deploying the wrong source code.

Do you currently have the `Hello, world!` code git pushed, and you're trying to local push the alternative source? It's plausible that there's something wrong in the supervisor on the device, which means it keeps starting up the wrong application somehow... You could try provisioning a new device in a new application, without that source, and that would rule that out entirely. If you do that and you're still seeing the Hello World message, it's definitely coming from your local source folder somehow.

This does sound very odd and confusing though. If you don't manage to get any further clues, enable support access to the device (there's a button on the actions page), post its dashboard URL here, and I'll take a closer look and see if I can work out what's going on.

**Comment by zrzka** [comment]
Nope, _Hello, world!_ was never pushed. `resin` origin `master` contains thermometer, older version, but no _Hello, world!_.

I've got additional devices here. Going to add them to the fleet. One in local development mode, another one in production mode. We'll see what happens.

**Comment by zrzka** [comment]
@pimterry this is definitely weird ...

1) Device `3a2bbb818b7593944bcbad085e70705e` (named `local`)

* development & local mode

_Hallo, world!_ no matter what I do.

2) New device `d54b4cee8763ec270b8e60500a1f92df`, named `production`

* production, no local mode

Just flashed, added to the fleet (for the first time), first reboot, thermometer with UI, `git push resin master`, reboot and _Hallo, world!_.

3) New device `7120336ebbb87d2905f9cfbbc3fd1f28`, named `development`

* development, no local mode

Just flashed, added to the fleet (for the first time), first reboot, thermometer with UI, `git push resin master` (see 2), reboot and _Hallo, world!_.

Granted one week access to all these devices.

Origin `resin` branch `master` == https://github.com/zrzka/rust-thermometer `master`

[main.rs history](https://github.com/zrzka/rust-thermometer/commits/master/src/main.rs). There's no _Hallo, world!_.

**Comment by pimterry** [comment]
This definitely looks like an issue in your build.

If I SSH into the running container on the local device (SSH into the OS, `balena exec -it local-app /bin/bash`), and run `/usr/src/app/launch-app.sh`, then it really does print `Hello, world!`, and running `grep -R 'Hello, world'`, you'll see that `target/debug/thermometer` contains exactly that string. Looking at the history of that container (`balena history local-app`), every build step after the base image was run fresh today, so it's something in the source you're building that's causing this.

It's hard to say exactly why, but it really looks like something in your source is intentionally logging that message. Looking at [your Dockerfile](https://github.com/zrzka/rust-thermometer/blob/master/Dockerfile.template), it looks like you're building the `dependencies` stage including the Hello World code (you're building a totally fresh app), and then copying in your real source and rebuilding, and that's not correctly rebuilding as you're expecting. I'm no Rust expert, so I'm not really sure how Rust's incremental compilation & build caching etc are supposed to work there, but I'm fairly confident that's your problem.

You can test this fairly quickly either way - if you add a `rm -r target/` before your last `cargo build` to make sure that builds from scratch, I bet everything will start working nicely.

**Comment by zrzka** [comment]
Mea culpa, searching at the wrong place. I thought that the _Hello, world!_ comes from [example project](https://github.com/resin-io-projects/resin-rust-hello-world/blob/master/src/main.rs) which was deployed as a first thing to test. But I completely forget that I did add `cargo new ...`, which creates same file with the same output.

Sorry for this. I'll definitely have to buy you some 🍻 in Barcelona 😉

**Comment by pimterry** [comment]
No worries, glad you've got it sorted!

**Comment by zrzka** [comment]
![img_0680](https://user-images.githubusercontent.com/1084172/42168462-50aa3fec-7e11-11e8-86c2-b06eacbf919d.jpg)

Yep, running in all modes! Will post an update here when I solve dependencies build caching, so, others can learn as well.

**Comment by zrzka** [comment]
In case anyone is going to read this issue and has same _problem_, here's the fixed version:

* [Dockerfile.template](https://github.com/zrzka/rust-thermometer/blob/cd388515c9f159710aa406890fadeb374a1c61c2/Dockerfile.template)
* [local-push.sh](https://github.com/zrzka/rust-thermometer/blob/cd388515c9f159710aa406890fadeb374a1c61c2/scripts/local-push.sh)

Works with `local push` and fleet deployment (`git push resin master`) as well. Cached dependencies, does not include build tools in the final image, source code, ...
