### ISSUE TITLE
resin local push for .Net Core app gives "exec format error"

### ISSUE THREAD

**Issue by FreeWillaert** [resin-io/resin-cli#916]
- **resin-cli version:7.6.2**
- **Operating system and architecture:macOS 10.12.6 / raspberry pi 3**

I have an app that is based on https://github.com/resin-io-playground/resin-dotnet-hello-world
(noting only that I updated to dotnet-sdk-2.1)

Everything is fine when deploying through the resin.io platform, using
`git push resin master:resin-emulated`

Now attempting to do a local deployment, I first changed my Dockerfile.template to Dockerfile, replacing %%RESIN_MACHINE_NAME%% by raspberrypi3 - that seems ok.

However, when I run
`$ sudo resin local push 192.168.0.21 -s .`

This fails with error: exec user process caused "exec format error" (full error pasted at the bottom)

Some thoughts:
- I think this is the same error as I had some time ago when deploying through resin but without 'resin-emulated', but I'm not sure
- I can do a `sudo resin build` without problems -- is there perhaps a way to deploy the resulting image locally?
- I found https://github.com/resin-io/resin-cli/issues/880 which sounds *very* similar but I have no 'cross build' commands in my Dockerfile. I'll paste my full Dockerfile at the bottom as well.

---

$ sudo resin local push 192.168.0.21 -s .
Password:
* Building..
- Stopping and removing any previous 'local-app' container
- Uploading build context & starting build...
Step 1/12 : FROM resin/amd64-fedora:25 AS build
 ---> acbe45f782d6
Step 2/12 : RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc &&     echo -e "[packages-microsoft-com-prod]\nname=packages-microsoft-com-prod \nbaseurl=https://packages.microsoft.com/yumrepos/microsoft-rhel7.3-prod\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc"     > /etc/yum.repos.d/dotnetdev.repo &&     dnf install -y libunwind libicu dotnet-sdk-2.1
 ---> Running in 1ca494687505
standard_init_linux.go:187: exec user process caused "exec format error"
Push failed. Error: The command '/bin/sh -c rpm --import https://packages.microsoft.com/keys/microsoft.asc &&     echo -e "[packages-microsoft-com-prod]\nname=packages-microsoft-com-prod \nbaseurl=https://packages.microsoft.com/yumrepos/microsoft-rhel7.3-prod\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc"     > /etc/yum.repos.d/dotnetdev.repo &&     dnf install -y libunwind libicu dotnet-sdk-2.1' returned a non-zero code: 1 Error: The command '/bin/sh -c rpm --import https://packages.microsoft.com/keys/microsoft.asc &&     echo -e "[packages-microsoft-com-prod]\nname=packages-microsoft-com-prod \nbaseurl=https://packages.microsoft.com/yumrepos/microsoft-rhel7.3-prod\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc"     > /etc/yum.repos.d/dotnetdev.repo &&     dnf install -y libunwind libicu dotnet-sdk-2.1' returned a non-zero code: 1
    at Stream.<anonymous> (/Users/Free/.nvm/versions/node/v8.10.0/lib/node_modules/resin-cli/node_modules/resin-sync/build/docker-utils.js:146:23)
    at emitOne (events.js:116:13)
    at Stream.emit (events.js:211:7)
    at drain (/Users/Free/.nvm/versions/node/v8.10.0/lib/node_modules/resin-cli/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/Users/Free/.nvm/versions/node/v8.10.0/lib/node_modules/resin-cli/node_modules/through/index.js:45:5)
    at Parser.parser.onToken (/Users/Free/.nvm/versions/node/v8.10.0/lib/node_modules/resin-cli/node_modules/JSONStream/index.js:129:18)
    at Parser.proto.write (/Users/Free/.nvm/versions/node/v8.10.0/lib/node_modules/resin-cli/node_modules/jsonparse/jsonparse.js:135:34)
    at Stream.<anonymous> (/Users/Free/.nvm/versions/node/v8.10.0/lib/node_modules/resin-cli/node_modules/JSONStream/index.js:21:12)
    at Stream.stream.write (/Users/Free/.nvm/versions/node/v8.10.0/lib/node_modules/resin-cli/node_modules/through/index.js:26:11)
    at IncomingMessage.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at IncomingMessage.Readable.push (_stream_readable.js:208:10)
    at HTTPParser.parserOnBody (_http_common.js:139:22)
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20) 

---

My Dockerfile:

```
FROM resin/amd64-fedora:25 AS build

# Using instructions from https://www.microsoft.com/net/core#linuxfedora
RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc && \
    echo -e "[packages-microsoft-com-prod]\nname=packages-microsoft-com-prod \nbaseurl=https://packages.microsoft.com/yumrepos/microsoft-rhel7.3-prod\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" \
    > /etc/yum.repos.d/dotnetdev.repo && \
    dnf install -y libunwind libicu dotnet-sdk-2.1

WORKDIR /usr/src/app
COPY ./src /usr/src/app
RUN dotnet publish -r linux-arm

FROM resin/raspberrypi3-debian:stretch

ENV INITSYSTEM on

WORKDIR /usr/src/app

# Install dependencies listed at https://github.com/dotnet/core/blob/master/Documentation/prereqs.md
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
    libunwind8 gettext libicu57 liblttng-ust0 libcurl3 libssl1.0.2 libuuid1 unzip cron && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy the standalone application
COPY --from=build /usr/src/app/Console/bin/Debug/netcoreapp2.1/linux-arm/publish /usr/src/app


# Schedule a download of appsettings.json every x minutes (the reload still does a compare to see if anything changed)
RUN echo "*/1 * * * * /usr/src/app/get-appsettings.sh" | crontab

CMD /usr/src/app/start.sh
```

**Comment by pimterry** [comment]
This error means you're trying to run binaries on one architecture that don't work there. In some environments you can emulate to work around this, but we don't support that with local mode: both because emulating on a device itself would be extremely slow, and because you shouldn't need to (you're running on the real target hardware - you shouldn't need to emulate anything).

In looks like your Dockerfile is dependent on building the first stage on an AMD64 machine, cross-compiling from there to ARM. Is that right? That's going to be the hard part here.

In theory, with a few tweaks you probably can manage emulation yourself within the Dockerfile to make this work (try the `cross-build-start/stop` commands from the issue you linked). Even if you do though I suspect you'll find that trying to emulate a AMD64 machine on a Raspberry Pi is a very slow process, so running that build step as-is on your device might not be practical at all.

Is there any way you can change your initial build step so that it uses an ARM base image directly, instead of cross-compiling? That would be the best solution to this (and it'd speed up your cloud builds quite a bit too, since you'd be able to use our native ARM infrastructure).

If not, then you'll need to look at ways to build your first stage locally, and then separately local push only the second stage. I think the easiest option for that is something like:

* Split your Dockerfile into two, one for each stage
* Write a script that:
	* Builds the first stage on your local machine
	* Copies out the `/usr/src/app/Console/bin/Debug/netcoreapp2.1/linux-arm/publish` file from the resulting image into your local source directory.
	* Local pushes to the device using the 2nd Dockerfile, which copies the `publish` file in from the source directory as part of its build.

With that, you'll effectively be building half locally and half on the device. It's a little awkward, and I haven't tried it myself, but it should work in theory. Let me know how it goes! This is definitely and interesting unusual case, I'd be very curious to know which of these options works for you.

**Comment by FreeWillaert** [comment]
Wonderful, thanks for the great explanation!
Now that I actually understand what the problem is, the solution was indeed trivial: remove the first stage from the Dockerfile, and add a script that publishes and then calls resin local start.

I'll paste both the script ad the Dockerfile for others who might find it useful.

Thanks!!

---

Dockerfile
```
FROM resin/raspberrypi3-debian:stretch

ENV INITSYSTEM on

WORKDIR /usr/src/app

# Install dependencies listed at https://github.com/dotnet/core/blob/master/Documentation/prereqs.md
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
    libunwind8 gettext libicu57 liblttng-ust0 libcurl3 libssl1.0.2 libuuid1 unzip cron && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy the standalone application
COPY ./src/Console/bin/Debug/netcoreapp2.1/linux-arm/publish /usr/src/app

# Schedule a download of appsettings.json every x minutes
RUN echo "*/5 * * * * /usr/src/app/get-appsettings.sh" | crontab

CMD /usr/src/app/start.sh
```


resin-deploy-local.sh
```
dotnet publish ./src -r linux-arm

resin local push 192.168.0.21 -s . --force-build
```
