### ISSUE TITLE
local configure broken on macOS since 7.8.2

### ISSUE THREAD

**Issue by zrzka** [resin-io/resin-cli#932]
7.8.1 works like a charm:

```bash
 2018-07-25 22:32:58 ⌚  Zrzka in ~
○ → sudo resin local configure ~/Downloads/resin-rust-thermometer-raspberrypi3-2.13.6+rev1-v7.14.0.img
? Network SSID (My_Wifi_Ssid)
```

7.8.2 and 7.8.3 not, stuck in a limbo, it's waiting for something, no output, nothing. Let me know how can I help if you have no macOS around.

**Comment by pimterry** [comment]
It's been a little while now @zrzka, but does this work now if you retry?

I've only just managed to find time & an OSX machine to do more thorough testing, but now everything seems fine to work fine for me with:

* CLI: 7.9.2
* Node: 8.11.4
* OSX: 10.11.6

It's surprising we haven't had any other user reports in the meantime too, if it's an ongoing issue. If you're still seeing it, can you tell me a bit more about your environment? Are you using an unusual shell by any chance? I think I've seen similar issues in some cases like that elsewhere.

**Comment by zrzka** [comment]
@pimterry last version I did test was 7.8.3. Here're the results of newer versions:

* 7.8.4 - doesn't work
* 7.8.5 - doesn't work
* 7.8.6 - doesn't work
* 7.9.0 - doesn't work
* 7.9.1 - doesn't work
* 7.9.2 - doesn't work

Downgraded to 7.8.1 and it works. I don't have anything weird installed ...

* I do use iTerm.app, but I did test all these versions in macOS Terminal.app as well
* I do use bash

Versions:

* bash 3.2.57
* node v8.11.3
* macOS 10.13.6 (17G65)

The only difference here is node (8.11.3 vs 8.11.4) and macOS version (10.13.6 vs 10.11.6). Did update to 8.11.4 and no luck, still nothing.

It's stuck [here](https://github.com/resin-io/resin-cli/blob/master/lib/actions/local/configure.coffee#L221). `reconfix.readConfiguration` is called and `.then(getConfiguration)` is never called. So the problem is inside `readConfiguration`.

When I check diff between 7.8.1 (works) and 7.8.2 (doesn't work), there was a reconfix update 0.0.3 -> 0.1.0. Which kind of confirms reconfix issue?

**Comment by pimterry** [comment]
Further details, for reference:

* This only happens on dashboard-downloaded images with wifi configured.
* It appears to be caused by ext2fs, which hangs when trying to read more files in parallel than the threads Node has been configured with. See https://github.com/resin-io/node-ext2fs/issues/46 for details.
* We can fix by increasing the thread count (`UV_THREADPOOL_SIZE=64`) in the short-term or reading sequentially, and medium-term we need to resolve the underlying deadlock itself.

**Comment by zrzka** [comment]
Confirmed, 7.9.3 fixes my issue and it works like a charm.
