### ISSUE TITLE
Missing image resin-cli preload uninformative 

### ISSUE THREAD

**Issue by Davidnet** [resin-io/resin-cli#974]
- **resin-cli version:** 7.10 
- **Operating system and architecture:**
Ubuntu x86-64

Hi I'm trying to follow the resin preload program for the Jetson tx2, but I'm always encountering 'Missing Image' the img file I already verified is there and I have access to my devices and the app id.

Any ideas of what is going on? thanks

**Comment by pimterry** [comment]
I'm not sure I'm afraid. @zvin do you know what might cause this?

**Comment by zvin** [comment]
@Davidnet what command are you running ?

**Comment by zvin** [comment]
@Davidnet the correct command would be
```
resin preload resin-XXXXXXXXX-jetson-tx2-2.17.0+rev1-v7.16.6.img --app $APP_NUMBER
```

**Comment by zvin** [comment]
You can run `resin preload --help` for all available options.

**Comment by Davidnet** [comment]
Awesome! Is there any guidelines that I can do for adding that example to the documentation, I think it would save a time. Thanks you're awesome!
